### ISSUE TITLE
POST /webdriver/sessions fails with standard input

### ISSUE THREAD

**Issue by willglynn** [browserless/chrome#1000]
**Describe the bug**
`POST /webdriver/sessions` fails with standard input.

**To Reproduce**

1.  Make a file `body.json` with the following content:

```json
{
  "capabilities": {
    "alwaysMatch": {
      "desiredCapabilities": {
        "javascriptEnabled": true
      },
      "goog:chromeOptions": {
        "w3c": true
      },
      "pageLoadStrategy": "normal"
    },
    "firstMatch": [
      {
      }
    ]
  }
}
```

This request body was produced by my client library and appears to conform to the [W3C WebDriver spec](https://www.w3.org/TR/webdriver/#new-session).

2. In one terminal, `docker run -i -p 3000:3000 browserless/chrome`
3. In another terminal, `curl -v -H 'Content-Type: application/json' -d body.json http://localhost:3000/webdriver/session`

**Expected behavior**

`curl` receives an HTTP response containing a JSON object with `sessionId` and `capabilities`.

**Actual behavior**

`docker` displays:

```
Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'browserless.blockAds' of undefined
      at Object.exports.normalizeWebdriverStart (/usr/src/app/build/utils.js:237:50)
      at async BrowserlessServer.handleWebDriver (/usr/src/app/build/browserless.js:297:38)
} reason: TypeError: Cannot read property 'browserless.blockAds' of undefined
    at Object.exports.normalizeWebdriverStart (/usr/src/app/build/utils.js:237:50)
    at async BrowserlessServer.handleWebDriver (/usr/src/app/build/browserless.js:297:38)
```

60 seconds later, `curl` indicates the server closed the connection without sending an HTTP response.

**Additional context**

* `normalizeWebdriverStart()` [assumes](https://github.com/browserless/chrome/blob/cba7535b9e6a84af127ccd361fd7be083ea00e61/src/utils.ts#L321-L323) that the request always contains a `desiredCapabilities` property, raising an exception if it's missing, and
* Unexpected errors generated here do not produce a `500 Internal Server Error` response

**Comment by joelgriffith** [comment]
Thanks for this -- we have a nasty compatibility layer to conform with all the drivers out there. I'll use your example as a test-case and we'll get this fixed since it's a legitimate bug

**Comment by lonkle** [comment]
Unrelated, but I hate that only now, @joelgriffith, am I realizing that your profile picture isn't a bug... Okay, this is my first post but I've been following browserless' Github for awhile now. 😂

**Comment by mileszim** [comment]
Can second this-- @willglynn I set up a temporary workaround:

<details><summary>1. Modify the Dockerfile</summary>
<p>

```docker
FROM browserless/chrome:latest
USER root

RUN rm build/utils.js
COPY build/utils.js build/utils.js

CMD ["./start.sh"]
```
</p>
</details>

<details><summary>2. Modify the build/utils.js file</summary>
<p>

```javascript
... 
    // these should be near line 237
    const blockAds = !!parsed.desiredCapabilities ? !!parsed.desiredCapabilities['browserless.blockAds'] : null;
    const trackingId = !!parsed.desiredCapabilities ? parsed.desiredCapabilities['browserless.trackingId'] : null;
    const pauseOnConnect = !!parsed.desiredCapabilities ? !!parsed.desiredCapabilities['browserless.pause'] : null;
...
```
</p>
</details>

Hope this helps for now! Here's the full build/utils.js if you want it:

<details><summary>build/utils.js</summary>
<p>

```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.dedent = exports.canPreboot = exports.isWebdriver = exports.isWebdriverClose = exports.isWebdriverStart = exports.getTimeoutParam = exports.parseRequest = exports.clearBrowserlessDataDirs = exports.getUserDataDir = exports.fnLoader = exports.normalizeWebdriverStart = exports.sleep = exports.generateChromeTarget = exports.fetchJson = exports.isAuthorized = exports.isWebdriverAuthorized = exports.codeCookieName = exports.tokenCookieName = exports.queryValidation = exports.bodyValidation = exports.asyncWebHandler = exports.asyncWsHandler = exports.getBasicAuthToken = exports.buildWorkspaceDir = exports.id = exports.getDebug = exports.rimraf = exports.mkdir = exports.writeFile = exports.readdir = exports.lstat = exports.exists = exports.jsonProtocolPrefix = void 0;
const cookie = require("cookie");
const fs = require("fs");
const _ = require("lodash");
const node_fetch_1 = require("node-fetch");
const os = require("os");
const path = require("path");
const rmrf = require("rimraf");
const stream_1 = require("stream");
const url = require("url");
const util = require("util");
const constants_1 = require("./constants");
const config_1 = require("./config");
const dbg = require('debug');
const { CHROME_BINARY_LOCATION } = require('../env');
const mkdtemp = util.promisify(fs.mkdtemp);
const characters = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ';
exports.jsonProtocolPrefix = 'BROWSERLESS';
exports.exists = util.promisify(fs.exists);
exports.lstat = util.promisify(fs.lstat);
exports.readdir = util.promisify(fs.readdir);
exports.writeFile = util.promisify(fs.writeFile);
exports.mkdir = util.promisify(fs.mkdir);
exports.rimraf = util.promisify(rmrf);
exports.getDebug = (level) => dbg(`browserless:${level}`);
const webdriverSessionCloseReg = /^\/webdriver\/session\/((\w+$)|(\w+\/window))/;
const debug = exports.getDebug('system');
const legacyChromeOptionsKey = 'chromeOptions';
const w3cChromeOptionsKey = 'goog:chromeOptions';
const readFilesRecursive = async (dir, results = []) => {
    const [, parentDir] = dir.split(config_1.WORKSPACE_DIR);
    const workspaceDir = _.chain(parentDir)
        .split(path.sep)
        .compact()
        .head()
        .value();
    const files = await exports.readdir(dir);
    await Promise.all(files.map(async (file) => {
        const stats = await exports.lstat(path.join(dir, file));
        if (stats.isDirectory()) {
            return readFilesRecursive(path.join(dir, file), results);
        }
        results.push({
            created: stats.birthtime,
            isDirectory: stats.isDirectory(),
            name: file,
            path: path.join('/workspace', parentDir, file),
            size: stats.size,
            workspaceId: workspaceDir || null,
        });
        return results;
    }));
    return results;
};
exports.id = (prepend = '') => prepend + Array.from({ length: prepend ? 32 - prepend.length : 32 }, () => characters.charAt(Math.floor(Math.random() * characters.length))).join('');
exports.buildWorkspaceDir = async (dir) => {
    const hasDownloads = await exports.exists(dir);
    if (!hasDownloads) {
        return null;
    }
    return await readFilesRecursive(dir);
};
exports.getBasicAuthToken = (req) => {
    const header = req.headers.authorization || '';
    const token = header.split(/\s+/).pop() || '';
    return Buffer.from(token, 'base64').toString().replace(':', '');
};
exports.asyncWsHandler = (handler) => {
    return (req, socket, head) => {
        Promise.resolve(handler(req, socket, head))
            .catch((error) => {
            debug(`Error in WebSocket handler: ${error}`);
            socket.write([
                'HTTP/1.1 400 Bad Request',
                'Content-Type: text/plain; charset=UTF-8',
                'Content-Encoding: UTF-8',
                'Accept-Ranges: bytes',
                'Connection: keep-alive',
            ].join('\n') + '\n\n');
            socket.write(Buffer.from('Bad Request, ' + error.message));
            socket.end();
        });
    };
};
exports.asyncWebHandler = (handler) => {
    return (req, res) => {
        Promise.resolve(handler(req, res))
            .catch((error) => {
            debug(`Error in route handler: ${error}`);
            res.status(400).send(error.message);
        });
    };
};
exports.bodyValidation = (schema) => {
    return (req, res, next) => {
        const header = req.header('content-type');
        if (header && !header.includes('json')) {
            return next();
        }
        const result = schema.validate(req.body);
        if (result.error) {
            debug(`Malformed incoming request: ${result.error}`);
            return res.status(400).send(result.error.details);
        }
        req.body = result.value;
        return next();
    };
};
exports.queryValidation = (schema) => {
    return (req, res, next) => {
        let inflated = null;
        if (typeof req.query.body !== 'string') {
            return res.status(400).send(`The query-parameter "body" is required, and must be a URL-encoded JSON object.`);
        }
        try {
            inflated = JSON.parse(req.query.body);
        }
        catch (_a) {
            inflated = null;
        }
        if (!inflated) {
            return res.status(400).send(`The query-parameter "body" is required, and must be a URL-encoded JSON object.`);
        }
        const result = schema.validate(inflated);
        if (result.error) {
            debug(`Malformed incoming request: ${result.error}`);
            return res.status(400).send(result.error.details);
        }
        req.body = result.value;
        return next();
    };
};
exports.tokenCookieName = 'browserless_token';
exports.codeCookieName = 'browserless_code';
exports.isWebdriverAuthorized = (req, body, token) => {
    const authToken = (exports.getBasicAuthToken(req) ||
        _.get(body, ['desiredCapabilities', 'browserless.token'], null));
    if (authToken !== token) {
        return false;
    }
    return true;
};
exports.isAuthorized = (req, token) => {
    const cookies = cookie.parse(req.headers.cookie || '');
    const parsedUrl = req.parsed;
    const authToken = _.get(parsedUrl, 'query.token', null) ||
        exports.getBasicAuthToken(req) ||
        cookies[exports.tokenCookieName];
    if (authToken !== token) {
        return false;
    }
    return true;
};
exports.fetchJson = (url, opts) => node_fetch_1.default(url, opts)
    .then((res) => {
    if (!res.ok) {
        throw res;
    }
    return res.json();
});
exports.generateChromeTarget = () => {
    return `/devtools/page/${exports.id(exports.jsonProtocolPrefix)}`;
};
exports.sleep = (time = 0) => {
    return new Promise((resolve) => {
        setTimeout(resolve, time);
    });
};
const safeParse = (maybeJson) => {
    try {
        return JSON.parse(maybeJson);
    }
    catch (_a) {
        return null;
    }
};
exports.normalizeWebdriverStart = async (req) => {
    const body = await readRequestBody(req);
    const parsed = safeParse(body);
    let isUsingTempDataDir;
    if (_.has(parsed, ['desiredCapabilities', legacyChromeOptionsKey])) {
        parsed.desiredCapabilities[w3cChromeOptionsKey] = _.cloneDeep(parsed.desiredCapabilities[legacyChromeOptionsKey]);
        delete parsed.desiredCapabilities[legacyChromeOptionsKey];
    }
    if (_.has(parsed, ['capabilities', 'alwaysMatch', legacyChromeOptionsKey])) {
        parsed.capabilities.alwaysMatch[w3cChromeOptionsKey] = _.cloneDeep(parsed.capabilities.alwaysMatch[legacyChromeOptionsKey] ||
            parsed.desiredCapabilities[w3cChromeOptionsKey]);
        delete parsed.capabilities.alwaysMatch[legacyChromeOptionsKey];
    }
    if (_.has(parsed, ['capabilities', 'firstMatch']) &&
        _.some(parsed.capabilities.firstMatch, (opt) => opt[legacyChromeOptionsKey])) {
        _.each(parsed.capabilities.firstMatch, (opt) => {
            if (opt[legacyChromeOptionsKey]) {
                opt[w3cChromeOptionsKey] = _.cloneDeep(opt[legacyChromeOptionsKey]);
                delete opt[legacyChromeOptionsKey];
            }
        });
    }
    const launchArgs = _.uniq([
        ..._.get(parsed, ['desiredCapabilities', w3cChromeOptionsKey, 'args'], []),
        ..._.get(parsed, ['capabilities', 'alwaysMatch', w3cChromeOptionsKey, 'args'], []),
        ..._.get(parsed, ['capabilities', 'firstMatch', '0', w3cChromeOptionsKey, 'args'], []),
    ]);
    isUsingTempDataDir = !launchArgs.some((arg) => arg.startsWith('--user-data-dir'));
    const browserlessDataDir = isUsingTempDataDir ? await exports.getUserDataDir() : null;
    if (_.has(parsed, ['desiredCapabilities', w3cChromeOptionsKey])) {
        if (isUsingTempDataDir) {
            parsed.desiredCapabilities[w3cChromeOptionsKey].args = parsed.desiredCapabilities[w3cChromeOptionsKey].args || [];
            parsed.desiredCapabilities[w3cChromeOptionsKey].args.push(`--user-data-dir=${browserlessDataDir}`);
        }
        parsed.desiredCapabilities[w3cChromeOptionsKey].binary = CHROME_BINARY_LOCATION;
    }
    if (_.has(parsed, ['capabilities', 'alwaysMatch', w3cChromeOptionsKey])) {
        if (isUsingTempDataDir) {
            parsed.capabilities.alwaysMatch[w3cChromeOptionsKey].args = parsed.capabilities.alwaysMatch[w3cChromeOptionsKey].args || [];
            parsed.capabilities.alwaysMatch[w3cChromeOptionsKey].args.push(`--user-data-dir=${browserlessDataDir}`);
        }
        parsed.capabilities.alwaysMatch[w3cChromeOptionsKey].binary = CHROME_BINARY_LOCATION;
    }
    if (_.has(parsed, ['capabilities', 'firstMatch']) &&
        _.some(parsed.capabilities.firstMatch, (opt) => opt[w3cChromeOptionsKey])) {
        _.each(parsed.capabilities.firstMatch, (opt) => {
            if (opt[w3cChromeOptionsKey]) {
                if (isUsingTempDataDir) {
                    opt[w3cChromeOptionsKey].args = opt[w3cChromeOptionsKey].args || [];
                    opt[w3cChromeOptionsKey].args.push(`--user-data-dir=${browserlessDataDir}`);
                }
                opt[w3cChromeOptionsKey].binary = CHROME_BINARY_LOCATION;
            }
        });
    }
    const stringifiedBody = JSON.stringify(parsed, null, '');
    req.headers['content-length'] = stringifiedBody.length.toString();
    attachBodyToRequest(req, stringifiedBody);
    const blockAds = !!parsed.desiredCapabilities ? !!parsed.desiredCapabilities['browserless.blockAds'] : null;
    const trackingId = !!parsed.desiredCapabilities ? parsed.desiredCapabilities['browserless.trackingId'] : null;
    const pauseOnConnect = !!parsed.desiredCapabilities ? !!parsed.desiredCapabilities['browserless.pause'] : null;
    const windowSizeArg = launchArgs.find((arg) => arg.includes('window-size='));
    const windowSizeParsed = windowSizeArg && windowSizeArg.split('=')[1].split(',');
    let windowSize;
    if (Array.isArray(windowSizeParsed)) {
        const [width, height] = windowSizeParsed;
        windowSize = {
            width: +width,
            height: +height,
        };
    }
    return {
        body: parsed,
        params: {
            blockAds,
            trackingId,
            pauseOnConnect,
            windowSize,
            isUsingTempDataDir,
            browserlessDataDir,
        }
    };
};
const attachBodyToRequest = (req, body) => {
    const bufferStream = new stream_1.PassThrough();
    bufferStream.end(Buffer.from(body));
    Object.assign(req, bufferStream);
};
const readRequestBody = async (req) => {
    return new Promise((resolve) => {
        const body = [];
        let hasResolved = false;
        const resolveNow = (results) => {
            if (hasResolved) {
                return;
            }
            hasResolved = true;
            attachBodyToRequest(req, results);
            resolve(results);
        };
        req
            .on('data', (chunk) => body.push(chunk))
            .on('end', () => {
            const final = Buffer.concat(body).toString();
            if (hasResolved) {
                return;
            }
            resolveNow(final);
        })
            .on('aborted', () => {
            resolveNow(null);
        })
            .on('error', () => {
            resolveNow(null);
        });
    });
};
exports.fnLoader = (fnName) => fs.readFileSync(path.join(__dirname, '..', 'functions', `${fnName}.js`), 'utf8');
const browserlessDataDirPrefix = 'browserless-data-dir-';
exports.getUserDataDir = () => mkdtemp(path.join(os.tmpdir(), browserlessDataDirPrefix));
exports.clearBrowserlessDataDirs = () => exports.rimraf(path.join(os.tmpdir(), `${browserlessDataDirPrefix}*`));
exports.parseRequest = (req) => {
    const ret = req;
    const parsed = url.parse(req.url || '', true);
    ret.parsed = parsed;
    return ret;
};
exports.getTimeoutParam = (req) => {
    const payloadTimer = (req.method === 'POST' &&
        req.url &&
        req.url.includes('webdriver') &&
        req.hasOwnProperty('body')) ?
        _.get(req, ['body', 'desiredCapabilities', 'browserless.timeout'], null) :
        _.get(req, 'parsed.query.timeout', null);
    if (_.isArray(payloadTimer)) {
        return null;
    }
    const parsedTimer = _.parseInt(payloadTimer || '');
    if (_.isNaN(parsedTimer)) {
        return null;
    }
    if (parsedTimer === -1) {
        return undefined;
    }
    if (_.isNumber(parsedTimer)) {
        return parsedTimer;
    }
    return null;
};
exports.isWebdriverStart = (req) => {
    var _a;
    return ((_a = req.method) === null || _a === void 0 ? void 0 : _a.toLowerCase()) === 'post' && req.url === constants_1.WEBDRIVER_ROUTE;
};
exports.isWebdriverClose = (req) => {
    var _a;
    return ((_a = req.method) === null || _a === void 0 ? void 0 : _a.toLowerCase()) === 'delete' && webdriverSessionCloseReg.test(req.url || '');
};
exports.isWebdriver = (req) => {
    var _a;
    return (_a = req.url) === null || _a === void 0 ? void 0 : _a.includes(constants_1.WEBDRIVER_ROUTE);
};
exports.canPreboot = (incoming, defaults) => {
    if (!_.isUndefined(incoming.headless) && incoming.headless !== defaults.headless) {
        return false;
    }
    if (!_.isUndefined(incoming.args) && _.difference(incoming.args, defaults.args).length) {
        return false;
    }
    if (!_.isUndefined(incoming.ignoreDefaultArgs)) {
        if (typeof incoming.ignoreDefaultArgs !== typeof defaults.ignoreDefaultArgs) {
            return false;
        }
        if (Array.isArray(incoming.ignoreDefaultArgs) && Array.isArray(defaults.ignoreDefaultArgs)) {
            return !_.difference(incoming.ignoreDefaultArgs, defaults.ignoreDefaultArgs).length;
        }
        if (incoming.ignoreDefaultArgs !== defaults.ignoreDefaultArgs) {
            return false;
        }
    }
    if (!_.isUndefined(incoming.userDataDir) && incoming.userDataDir !== defaults.userDataDir) {
        return false;
    }
    return true;
};
exports.dedent = (strings, ...values) => {
    const raw = Array.isArray(strings) ? strings : [strings];
    let result = '';
    for (let i = 0; i < raw.length; i++) {
        result += raw[i]
            .replace(/\\\n[ \t]*/g, '')
            .replace(/\\`/g, '`');
        if (i < values.length) {
            result += values[i];
        }
    }
    const lines = result.split('\n');
    let mIndent = null;
    lines.forEach(l => {
        const m = l.match(/^(\s+)\S+/);
        if (m) {
            const indent = m[1].length;
            if (!mIndent) {
                mIndent = indent;
            }
            else {
                mIndent = Math.min(mIndent, indent);
            }
        }
    });
    if (mIndent !== null) {
        const m = mIndent;
        result = lines.map(l => l[0] === ' ' ? l.slice(m) : l).join('\n');
    }
    return result
        .trim()
        .replace(/\\n/g, '\n');
};

```
</p>
</details>

**Comment by joelgriffith** [comment]
Should be fixed in: https://github.com/browserless/chrome/pull/1059
