### ISSUE TITLE
Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory

### ISSUE THREAD

**Issue by OwaisSiddiqui** [browserless/chrome#1472]
**Describe the bug**
I am running the browserless Docker on an AWS ECS Task. I get the error `Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory` sometimes when I run my script which just launches 5 Puppeteer browsers at a time to scrape a website. I also launch the Puppeteer browsers with the query parameters: `?stealth&headless=false`.

Puppeteer Docker configuration:

```
2021-05-11T17:23:19.470Z browserless:server {
--
CONNECTION_TIMEOUT: 300000,
MAX_CONCURRENT_SESSIONS: 50,
QUEUE_LENGTH: 50,
SINGLE_RUN: false,
CHROME_REFRESH_TIME: 1800000,
KEEP_ALIVE: false,
DEFAULT_BLOCK_ADS: false,
DEFAULT_HEADLESS: true,
DEFAULT_LAUNCH_ARGS: [
'--proxy-server=direct://”,”—proxy-bypass-list=*',
'--disable-canvas-aa',
'--disable-2d-canvas-clip-aa',
'--disable-gl-drawing-for-tests',
'--disable-dev-shm-usage',
'--no-zygote',
'--use-gl=swiftshader',
'--enable-webgl',
'--hide-scrollbars',
'--mute-audio',
'--no-first-run',
'--disable-infobars',
'--disable-breakpad',
'--window-size=100,100',
'--user-data-dir=./chromeData',
'--no-sandbox',
'--disable-setuid-sandbox'
],
DEFAULT_IGNORE_DEFAULT_ARGS: false,
DEFAULT_IGNORE_HTTPS_ERRORS: false,
DEFAULT_DUMPIO: false,
DEFAULT_STEALTH: false,
DEFAULT_USER_DATA_DIR: undefined,
PREBOOT_CHROME: false,
DEBUG: 'browserless*',
DISABLED_FEATURES: [],
ENABLE_CORS: false,
ENABLE_API_GET: false,
TOKEN: null,
ENABLE_HEAP_DUMP: false,
ALLOW_FILE_PROTOCOL: false,
DISABLE_AUTO_SET_DOWNLOAD_BEHAVIOR: false,
FUNCTION_BUILT_INS: [ 'url' ],
FUNCTION_ENABLE_INCOGNITO_MODE: true,
FUNCTION_EXTERNALS: [ 'lighthouse', 'node-pdftk', 'sharp' ],
WORKSPACE_DIR: '/usr/src/app/workspace',
WORKSPACE_DELETE_EXPIRED: false,
WORKSPACE_EXPIRE_DAYS: 30,
FAILED_HEALTH_URL: null,
QUEUE_ALERT_URL: null,
REJECT_ALERT_URL: null,
TIMEOUT_ALERT_URL: null,
ERROR_ALERT_URL: null,
SESSION_CHECK_FAIL_URL: null,
PRE_REQUEST_HEALTH_CHECK: false,
EXIT_ON_HEALTH_FAILURE: true,
MAX_CPU_PERCENT: 99,
MAX_MEMORY_PERCENT: 99,
METRICS_JSON_PATH: null,
HOST: '0.0.0.0',
PORT: 3000,
SOCKET_CLOSE_METHOD: 'http',
PROXY_URL: undefined,
MAX_PAYLOAD_SIZE: '5mb'
} Final configuration
```

Logs (where the error shows up):
```
2021-05-11T17:29:23.859Z browserless:chrome-helper Chrome PID: 8196
--
2021-05-11T17:29:24.338Z browserless:system Error: Failed to launch the browser process!
[8315:8388:0511/172924.252484:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
at onClose (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
at ChildProcess.<anonymous> (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:184:79)
at ChildProcess.emit (events.js:327:22)
at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12) Issue launching Chrome, retries exhausted.
2021-05-11T17:29:24.338Z browserless:job Error: Failed to launch the browser process!
[8315:8388:0511/172924.252484:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
at onClose (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
at ChildProcess.<anonymous> (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:184:79)
at ChildProcess.emit (events.js:327:22)
at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12) 3FUFEWIBUSVBW0Z29W9KL7MTZRUZQE5S: Issue launching Chrome or proxying traffic, failing request
2021-05-11T17:29:24.339Z browserless:server 3FUFEWIBUSVBW0Z29W9KL7MTZRUZQE5S: Recording failed stat, cleaning up: "Failed to launch the browser process!
[8315:8388:0511/172924.252484:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
"
2021-05-11T17:29:24.339Z browserless:job 3FUFEWIBUSVBW0Z29W9KL7MTZRUZQE5S: Cleaning up job
2021-05-11T17:29:24.339Z browserless:job 3FUFEWIBUSVBW0Z29W9KL7MTZRUZQE5S: No browser to cleanup, exiting
2021-05-11T17:29:24.342Z browserless:job 3FUFEWIBUSVBW0Z29W9KL7MTZRUZQE5S: Websocket closed early, removing from queue and closing.
2021-05-11T17:29:24.342Z browserless:job 3FUFEWIBUSVBW0Z29W9KL7MTZRUZQE5S: Removing job from queue and cleaning up.
2021-05-11T17:29:24.342Z browserless:job 3FUFEWIBUSVBW0Z29W9KL7MTZRUZQE5S: Cleaning up job
2021-05-11T17:29:24.342Z browserless:job 3FUFEWIBUSVBW0Z29W9KL7MTZRUZQE5S: No browser to cleanup, exiting
2021-05-11T17:29:24.414Z browserless:chrome-helper Injecting download dir "/usr/src/app/workspace"
2021-05-11T17:29:24.421Z browserless:chrome-helper Injecting download dir "/usr/src/app/workspace"
2021-05-11T17:29:24.422Z browserless:chrome-helper Injecting download dir "/usr/src/app/workspace"
2021-05-11T17:29:24.425Z browserless:system Chrome launched 1376ms
2021-05-11T17:29:24.425Z browserless:job HPZBKVNYEFXQ648JG7H04JOEWOORXOC3: Starting session.
2021-05-11T17:29:24.425Z browserless:job HPZBKVNYEFXQ648JG7H04JOEWOORXOC3: Proxying request to /devtools/browser route: ws://127.0.0.1:36643/devtools/browser/12f05b01-f124-4f63-8af3-605ff7b3aee2.
2021-05-11T17:29:24.467Z browserless:chrome-helper Injecting download dir "/usr/src/app/workspace"
2021-05-11T17:29:24.589Z browserless:system Error: Failed to launch the browser process!
[8314:8428:0511/172924.468248:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
at onClose (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
at Interface.<anonymous> (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
at Interface.emit (events.js:327:22)
at Interface.close (readline.js:424:8)
at Socket.onend (readline.js:202:10)
at Socket.emit (events.js:327:22)
at endReadableNT (internal/streams/readable.js:1327:12)
at processTicksAndRejections (internal/process/task_queues.js:80:21) Issue launching Chrome, retries exhausted.
2021-05-11T17:29:24.589Z browserless:job Error: Failed to launch the browser process!
[8314:8428:0511/172924.468248:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
at onClose (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
at Interface.<anonymous> (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
at Interface.emit (events.js:327:22)
at Interface.close (readline.js:424:8)
at Socket.onend (readline.js:202:10)
at Socket.emit (events.js:327:22)
at endReadableNT (internal/streams/readable.js:1327:12)
at processTicksAndRejections (internal/process/task_queues.js:80:21) CQAC3NSFT5V5NPY4NKDRQL0CRIFYRA0F: Issue launching Chrome or proxying traffic, failing request
2021-05-11T17:29:24.590Z browserless:server CQAC3NSFT5V5NPY4NKDRQL0CRIFYRA0F: Recording failed stat, cleaning up: "Failed to launch the browser process!
[8314:8428:0511/172924.468248:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
"
2021-05-11T17:29:24.590Z browserless:job CQAC3NSFT5V5NPY4NKDRQL0CRIFYRA0F: Cleaning up job
2021-05-11T17:29:24.590Z browserless:job CQAC3NSFT5V5NPY4NKDRQL0CRIFYRA0F: No browser to cleanup, exiting
2021-05-11T17:29:24.592Z browserless:job CQAC3NSFT5V5NPY4NKDRQL0CRIFYRA0F: Websocket closed early, removing from queue and closing.
2021-05-11T17:29:24.592Z browserless:job CQAC3NSFT5V5NPY4NKDRQL0CRIFYRA0F: Removing job from queue and cleaning up.
2021-05-11T17:29:24.592Z browserless:job CQAC3NSFT5V5NPY4NKDRQL0CRIFYRA0F: Cleaning up job
2021-05-11T17:29:24.592Z browserless:job CQAC3NSFT5V5NPY4NKDRQL0CRIFYRA0F: No browser to cleanup, exiting
2021-05-11T17:29:24.742Z browserless:chrome-helper Injecting download dir "/usr/src/app/workspace"
2021-05-11T17:29:24.783Z browserless:chrome-helper Injecting download dir "/usr/src/app/workspace"
2021-05-11T17:29:25.706Z browserless:server HPZBKVNYEFXQ648JG7H04JOEWOORXOC3: Recording successful stat and cleaning up.
2021-05-11T17:29:25.706Z browserless:job HPZBKVNYEFXQ648JG7H04JOEWOORXOC3: Cleaning up job
2021-05-11T17:29:25.706Z browserless:job HPZBKVNYEFXQ648JG7H04JOEWOORXOC3: Browser not needed, closing
2021-05-11T17:29:25.706Z browserless:chrome-helper Shutting down browser with close command
2021-05-11T17:29:25.707Z browserless:server Current workload complete.
2021-05-11T17:29:25.778Z browserless:chrome-helper Browser process exited with code 0 and signal null, cleaning up
2021-05-11T17:29:25.908Z browserless:chrome-helper Sending SIGKILL signal to browser process 8196
2021-05-11T17:29:25.913Z browserless:job HPZBKVNYEFXQ648JG7H04JOEWOORXOC3: Browser cleanup complete.
```

**To Reproduce**
1. Setup a AWS ECS Task and run it
2. Use its public IP to create the web socket link to launch browsers from it
3. Run around 5 browsers with `?stealth&headless=false` as query parameters at a time and sometimes this error shows up

**Expected behavior**
To expect this error not to show up randomly.

**Desktop (please complete the following information):**
 - OS: AWS ECS Task and Mac OS for my own machine
 - Browser: Chrome (Puppeteer)
 - Version: Latest browserless Docker container (push it on April 23, 2021 03:54:17 AM (UTC-04) to the AWS ECR)

**Comment by OwaisSiddiqui** [comment]
I just removed all the environment variables I had and set it only:

```
CONNECTION_TIMEOUT: 300000,
MAX_CONCURRENT_SESSIONS: 50,
QUEUE_LENGTH: 50
```
and I didn't the get the error so far.
