### ISSUE TITLE
Unable to pass in parameters to fake audio device

### ISSUE THREAD

**Issue by paulseto** [browserless/chrome#1764]
**Describe the bug**
Pass in parameters when connecting to fake an audio device but receive an error indicating device not found.

```
const launch_args = [
	"--use-fake-ui-for-media-stream",
	"--use-fake-device-for-media-stream",
	"--no-sandbox",
	"--disable-setuid-sandbox",
	"--disable-dev-shm-usage",
	"--mute-audio",
	"--disable-gpu",
];
//Also tested without launch_args.
browser = await puppeteer.connect({
	browserWSEndpoint: "ws://localhost:3000",
	args: launch_args,
});

//Use local chrome
// browser = await puppeteer.launch({
// 	headless: true,
// 	args: launch_args,
// });

page.on("console", (msg) => {
	for (let i = 0; i < msg.args().length; ++i) {
		console.log(`${i}: ${msg.args()[i]}`);
	}
});

await page.goto(join_url, { wait_until: "domcontentloaded" });
//After document loads, a popup appears prompting the user to connect audio.
button = await page.waitForXPath("//button[@aria-label='Microphone']", {
	visible: true,
	timeout: 30000, //30 sec is more than enough time even on a busy server.
});
await page.waitForTimeout(500);
await button.click();

//An echo test occurs where the user speaks and confirms they can hear themself by click on a thumbs up. When dialog //disappears, the client fully connected with two way audio. The client is connecting over UDP.  If a client firewall exists, the client //will connect over port 443 to a TURN server.
 
button = await page.waitForXPath("//button[@aria-label='Echo is audible']", {
	visible: true,
	timeout: 30000, //30 sec is more than enough time even on a busy server.
});
await page.waitForTimeout(500);
await button.click();

```
Eventually, will receive this error on the browser's console.
```
0: JSHandle:[%s:%s:%s:%s] %c%s%c: %s: %c%s %c%s
1: JSHandle:18
2: JSHandle:34
3: JSHandle:39
4: JSHandle:0745
5: JSHandle:color: Crimson
6: JSHandle:ERROR
7: JSHandle:color: DimGray
8: JSHandle:clientLogger
9: JSHandle:color: SteelBlue
10: JSHandle:Error getting microphone - {NotFoundError: Requested device not found}
11: JSHandle:color: DimGray; font-style: italic; font-size: 0.9em
12: JSHandle:https://bbb2.allthejelly.com/html5client/17e8e6c91a1aefa37d2b991249357ce7fb1a7cff.js?meteor_js_resource=true:329:1270127
Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at C:\Users\mrpau\projects\bbb_client_test_in_node\src\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:217:63
    at new Promise (<anonymous>)
    at CDPSession.send (C:\Users\mrpau\projects\bbb_client_test_in_node\src\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:216:16)
    at ExecutionContext._evaluateInternal (C:\Users\mrpau\projects\bbb_client_test_in_node\src\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:204:50)
    at ExecutionContext.evaluateHandle (C:\Users\mrpau\projects\bbb_client_test_in_node\src\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:155:21)
    at WaitTask.rerun (C:\Users\mrpau\projects\bbb_client_test_in_node\src\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:536:37)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**To Reproduce**
1. Go to [https://mconf.github.io/api-mate/](https://mconf.github.io/api-mate/)
2. Click on the create link on the right.
3. Copy the join as moderator link and update the join_url above.

**Expected behavior**
When using my local chrome with the launch parameters above.

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Windows 10 with Docker Desktop
 - Chrome
 - 98

**Smartphone (please complete the following information):**
 - Not applicable

**Additional context**
 -

**Comment by joelgriffith** [comment]
Do you happen to know if this works inside of puppeteer by itself without browserless? It could be an issue with the library
