### ISSUE TITLE
File uploaded to docker cannot be accessed by puppeteer

### ISSUE THREAD

**Issue by taewookim** [browserless/chrome#1859]
[Version] 1-chrome-stable

I can upload the file to the docker WORKSPACE folder via CURL, and I can see that the file is there (also via CURL).. but when I try to access via puppetter, file cannot be found:

1. upload to work space via
curl -X POST   http://127.0.0.1:3000/workspace   -F 'file=@test.jpg'

2. make sure it's there (curl -X GET  http://127.0.0.1:3000/workspace )
[{"created":"2021-09-09T04:54:22.861Z","isDirectory":false,"name":"test.jpg","path":"/workspace/test.jpg","size":26875,"workspaceId":null}]

3. However, when I try to access:
const inputUploadHandle = await this.page.$(selector);
inputUploadHandle.uploadFile("/workspace/test.jpg");

I'm getting:
Error: /workspace/test.jpg does not exist or is not readable

**Comment by namilkimfree** [comment]
I have a same issue.

**Comment by andyMrtnzP** [comment]
Hey, @taewookim, are you sharing data among volumes? Or how exactly are you accessing `/workspace/test.jpg` there? Also note that the Borwserless image runs on a non-root and non-privileged user, so this might as well be a privilege-related problem. Make sure that the dir and files have the correct access permissions, and then try to download the file via Puppeteer.

When you go to the container's bash (`docker exec -t -i ID /bin/bash`), are the files in the expected location? In our tests, they are indeed there.

**Comment by taewookim** [comment]
@andyMrtnzP 
> are you sharing data among volumes? 

Nope. Here's the exact docker command:

```
docker container prune -f

docker run \
	-e "DEFAULT_BLOCK_ADS=true" \
	-e "DEFAULT_IGNORE_HTTPS_ERRORS=true" \
	-e "MAX_CONCURRENT_SESSIONS=4" \
	-e "PREBOOT_CHROME=true" \
	-e "CONNECTION_TIMEOUT=1200000" \
	-e "EXIT_ON_HEALTH_FAILURE=true" \
	-e "KEEP_ALIVE=true" \
	-e "WORKSPACE_DELETE_EXPIRED=true" \
	-e "WORKSPACE_EXPIRE_DAYS=1" \
	-e "DEFAULT_LAUNCH_ARGS=[\"--ignore-certificate-errors\",\"--ignore-certifcate-errors-spki-list\", \"--no-sandbox\",\"--disable-gpu\",\"--start-maximized\", \"--start-fullscreen\", \"--disable-setuid-sandbox\",\"--disable-dev-shm-usage\",\"--window-size=1200,800\",\"--single-process\", \"--disable-infobars\",\"--disable-web-security\", \"--disable-features=IsolateOrigins,site-per-process\", \"--window-position=0,0\", \"--no-zygote\", \"--no-sandbox\", \"--user-agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36'\",\"--proxy-server=138.68.239.79:6969\"]" \
	-p 3000:3000  --name browserless  browserless/chrome:1-chrome-stable
```

I even tried mounting folder:

```
docker run \
	-e "DEFAULT_BLOCK_ADS=true" \
	-e "DEFAULT_IGNORE_HTTPS_ERRORS=true" \
	-e "MAX_CONCURRENT_SESSIONS=4" \
	-e "PREBOOT_CHROME=true" \
	-e "CONNECTION_TIMEOUT=1200000" \
	-e "EXIT_ON_HEALTH_FAILURE=true" \
	-e "KEEP_ALIVE=true" \
	-e "WORKSPACE_DELETE_EXPIRED=true" \
	-e "WORKSPACE_EXPIRE_DAYS=1" \
	-e "DEFAULT_LAUNCH_ARGS=[\"--ignore-certificate-errors\",\"--ignore-certifcate-errors-spki-list\", \"--no-sandbox\",\"--disable-gpu\",\"--start-maximized\", \"--start-fullscreen\", \"--disable-setuid-sandbox\",\"--disable-dev-shm-usage\",\"--window-size=1200,800\",\"--single-process\", \"--disable-infobars\",\"--disable-web-security\", \"--disable-features=IsolateOrigins,site-per-process\", \"--window-position=0,0\", \"--no-zygote\", \"--no-sandbox\", \"--user-agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36'\",\"--proxy-server=138.68.239.79:6969\"]" \
	-p 3000:3000 --name browserless  -v  $(pwd)/pup_workspace/:/workspace/ browserless/chrome:1-chrome-stable
```

>  Or how exactly are you accessing /workspace/test.jpg there?

Just plain code.

```
(async () => {
    
    try {
        
        var fs = require("fs"); // Load the filesystem module
        var stats = fs.statSync("/workspace/test.jpg")
        var fileSizeInBytes = stats.size;
        console.log(fileSizeInBytes)

    } catch (error) {
        console.log("[INTERNAL CATCH]");
        console.log(error);        

    }finally{
        console.log("[finally exit] ");
    }
})().catch((error) => {
    console.log("[EXTERNAL CATCH]");
    console.log(error);
    (async () => {
        process.exit(1);
    })();
});
```

This code, too, gives error:
```

[INTERNAL CATCH]
{ Error: ENOENT: no such file or directory, stat '/workspace/test.jpg'
    at Object.statSync (fs.js:855:3)
    at /home/osboxes/leadautomation/pup/test_workspace.js:46:24
    at process._tickCallback (internal/process/next_tick.js:68:7)
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/workspace/test.jpg' }
```

> Borwserless image runs on a non-root and non-privileged user, so this might as well be a privilege-related problem.
I just tested it on browerless running as non-root user, and behavior is identical

One thing.... if I restart docker, /workspace directory is empty (even if folder is mounted)

**Comment by andyMrtnzP** [comment]
> Just plain code.

Note that, when you upload a file, the `path` on which it is saved is relative to the docker container, not the host itself. So you will never find the files in the `path` provided on the host unless explicitly configured to do that. Please, connect to the image's bash with `docker exec -t -i ID /bin/bash`, `cd` to the `path` and see if the files are there.

**Comment by namilkimfree** [comment]
@andyMrtnzP 
```

docker run \
	-e "DEFAULT_BLOCK_ADS=true" \
	-e "DEFAULT_IGNORE_HTTPS_ERRORS=true" \
	-e "MAX_CONCURRENT_SESSIONS=4" \
	-e "PREBOOT_CHROME=true" \
	-e "CONNECTION_TIMEOUT=1200000" \
	-e "EXIT_ON_HEALTH_FAILURE=true" \
	-e "KEEP_ALIVE=true" \
	-e "WORKSPACE_DELETE_EXPIRED=true" \
	-e "WORKSPACE_EXPIRE_DAYS=1" \
	-e "DEFAULT_LAUNCH_ARGS=[\"--ignore-certificate-errors\",\"--ignore-certifcate-errors-spki-list\", \"--no-sandbox\",\"--disable-gpu\",\"--start-maximized\", \"--start-fullscreen\", \"--disable-setuid-sandbox\",\"--disable-dev-shm-usage\",\"--window-size=1200,800\",\"--single-process\", \"--disable-infobars\",\"--disable-web-security\", \"--disable-features=IsolateOrigins,site-per-process\", \"--window-position=0,0\", \"--no-zygote\", \"--no-sandbox\", \"--user-agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36'\",\"--proxy-server=138.68.239.79:6969\"]" \
	-p 3000:3000 --name browserless -v C:\Users\free\Desktop\browserless:/usr/src/app/workspace/ --restart always -d 
 browserless/chrome
```

browser less docker have image file in /usr/src/app/workspace/cat.png

![image](https://user-images.githubusercontent.com/44854923/140450780-7590673d-af61-4019-b0bb-92b330385c0a.png)


```
var imagePath = "/usr/src/app/workspace/cat.png";
await element.UploadFileAsync(value);
```
but don't upload image file

**Comment by taewookim** [comment]
> Please, connect to the image's bash with `docker exec -t -i ID /bin/bash`, `cd` to the `path` and see if the files are there.

After I open into docker container, which directory am I looking at?
i.e.... "ls /workspace/" ?

**Comment by andyMrtnzP** [comment]
Take a look to how you mirror the workspace data in your host

> 	-p 3000:3000 --name browserless -v C:\Users\free\Desktop\browserless:/usr/src/app/workspace/ --restart always -d 

and then, in your js file, you

> var imagePath = "/usr/src/app/workspace/cat.png";

when you should be accessing the path in your host, `C:\Users\free\Desktop\browserless\cat.png`. I ran a test mirroring the workspace dir on my host and was able successfully upload a file, giving the correct path on the host. You cannot access `/usr/src/app/workspace/cat.png` directly from your host.

Also, be careful when mirroring dirs if you are using WSL2, as a bad configuration could lead to a very poor performance.

**Comment by namilkimfree** [comment]
Then I'm going to /usr/src/app/workspace/cat.png Not there.
C:\Users\free\Desktop\browserless\cat.pngDo I need to proceed with uploading to ?

**Comment by andyMrtnzP** [comment]
Run a `docker run -t -i -v PATH_ON_YOUR_HOST:/usr/src/app/workspace/ browserless/chrome /bin/sh` , so you get bash access. Then cd to worspace and `echo "test" > hello.txt`, which should reflect on the `PATH_ON_YOUR_HOST` dir, and that's the file you should access with JS. 
By the same token, when you run the container normally mirroring on your host, any file you upload should also reflect on the host selected path.

**Comment by namilkimfree** [comment]
i did test 

1. await element.UploadFileAsync("C:\Users\free\Desktop\browserless\cat.png");    ->

![image](https://user-images.githubusercontent.com/44854923/140559024-5a7c949c-8476-4dab-b6fa-980b2f82056e.png)

2. await element.UploadFileAsync("/usr/src/app/workspace/cat.png");   ->
 
![image](https://user-images.githubusercontent.com/44854923/140558090-0e66a181-e168-453f-b33e-f5899455ef42.png)

**Comment by andyMrtnzP** [comment]
It seems you managed to upload the correct file, since it would have thrown an exception if the file didn't exist. Does the problem persist?

**Comment by namilkimfree** [comment]
element.UploadFileAsync("C:\Users\free\Desktop\browserless\cat.png");
This method is uploading files that are locally, not docker's. 
the problem is browserless 
/usr/src/app/workspace/cat.png The file is not being uploaded.

**Comment by andyMrtnzP** [comment]
Hey, @namilkimfree, are you using any special library to handle the container's file system? Because, otherwise, you cannot access the file outside the container's environment. That would explain why you can upload the file mirrored on your host (`C:\Users\free\Desktop\browserless\cat.png`) but the file in the container's filesystem (`/usr/src/app/workspace/cat.png`) throws an exception with `fs.statSync()`.

But if you are using a library to handle that, then you'd need to check the docs and see if you are handling it as expected.

**Comment by andyMrtnzP** [comment]
Closing this issue due to inactivity
