### ISSUE TITLE
When setting the pre-boot mode, an error occurs when the maximum number of sessions is set to 11 or more.  Windows Server 2019

### ISSUE THREAD

**Issue by namilkimfree** [browserless/chrome#1911]
**Describe the bug**
When setting the pre-boot mode, an error occurs when the maximum number of sessions is set to 11 or more.  Windows Server 2019

```
 ProtocolError: Protocol error (Target.setDiscoverTargets): Target closed.
    at /usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:75:24
    at new Promise (<anonymous>)
    at Connection.send (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:71:16)
    at Function.create (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Browser.js:121:26)
    at ChromeLauncher.launch (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:117:56)
    at async Object.launchChrome (/usr/src/app/build/chrome-helper.js:328:27)
    at async Promise.all (index 16)
    at async BrowserlessServer.startServer (/usr/src/app/build/browserless.js:184:9) Issue launching Chrome, retrying 1 times.

2021-11-19T17:22:01.757Z browserless:system TimeoutError: waiting for target failed: timeout 30000ms exceeded
    at Object.waitWithTimeout (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/helper.js:224:26)
    at Browser.waitForTarget (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Browser.js:309:45)
    at ChromeLauncher.launch (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:119:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.launchChrome (/usr/src/app/build/chrome-helper.js:328:27)

```

**To Reproduce**
1. docker run  ocker run -e "MAX_CONCURRENT_SESSIONS=11" -e "CONNECTION_TIMEOUT=1200000" -e "PREBOOT_CHROME=true" -p 3000:3000 --restart always --name browserless browserless/chrome on  Windows Server 2019 
2. check browseless log 

**Expected behavior**
The preboot should be successful.

**Screenshots**

![image](https://user-images.githubusercontent.com/44854923/142713511-814aae1d-cb22-4d10-b584-06dbf90d7037.png)

**Desktop (please complete the following information):**
 - OS: [Windows Server 2019]
 - Browser [Chrome]
 - Version [latest]

**Additional context**

**Comment by joelgriffith** [comment]
Usually this happens when the machine can’t handle that number of concurrent sessions looking at your logs it looks like chrome takes 8 seconds to start which is abnormally high). I’d recommend running less concurrent sessions or doing a more powerful machine/docker limits
