### ISSUE TITLE
Unable to launch chrome Getting Timeout

### ISSUE THREAD

**Issue by AnshulEng** [browserless/chrome#2091]
We are trying to use headless chrome with puppeteer, trying to spawn concurrent chrome instances in a PREBOOT mode via docker image, and then trying to connect using puppeteer.connect it is failing at time of browser launching in that image
we are using 
**docker image version - chrome:release-puppeteer-1.9.0
puppeteer core - 1.15.0**
and it is failing with : 
browserless:chrome-helper Launching Chrome with args: {
  "args": [
    "--no-sandbox",
    "--disable-dev-shm-usage",
    "--enable-logging",
    "--v1=1",
    "--user-data-dir=/tmp/browserless-data-dir-eqEbRl"
  ],
  "blockAds": false,
  "headless": true,
  "ignoreDefaultArgs": false,
  "ignoreHTTPSErrors": false,
  "pauseOnConnect": false,
  "executablePath": "/usr/bin/google-chrome",
  "handleSIGINT": false,
  "handleSIGTERM": false
}
2022-01-28T06:53:35.289Z browserless:system 
**TimeoutError: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r650583**
    at Timeout.onTimeout (/usr/src/app/node_modules/puppeteer/lib/Launcher.js:353:14)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10) Issue launching Chrome, retries exhausted.
(node:7) UnhandledPromiseRejectionWarning: TimeoutError: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r650583
    at Timeout.onTimeout (/usr/src/app/node_modules/puppeteer/lib/Launcher.js:353:14)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

**Comment by joelgriffith** [comment]
Unfortunately this is a pretty old tag, and this has been fixed in later versions. Closing
