### ISSUE TITLE
Protocol error (Runtime.callFunctionOn): Target closed

### ISSUE THREAD

**Issue by gajus** [browserless/chrome#253]
Stack trace:

```
Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at /srv/[redacted]/node_modules/puppeteer/lib/Connection.js:183:56
    at new Promise (<anonymous>)
    at CDPSession.send (/srv/[redacted]/node_modules/puppeteer/lib/Connection.js:182:12)
    at ExecutionContext._evaluateInternal (/srv/[redacted]/node_modules/puppeteer/lib/ExecutionContext.js:107:44)
    at ExecutionContext.evaluateHandle (/srv/[redacted]/node_modules/puppeteer/lib/ExecutionContext.js:57:17)
    at ExecutionContext.<anonymous> (/srv/[redacted]/node_modules/puppeteer/lib/helper.js:112:23)
    at WaitTask.rerun (/srv/[redacted]/node_modules/puppeteer/lib/DOMWorld.js:582:65)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
  -- ASYNC --
    at Frame.<anonymous> (/srv/[redacted]/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.waitForSelector (/srv/[redacted]/node_modules/puppeteer/lib/Page.js:1044:29)
    at /srv/[redacted]/dist/countries/de/[redacted].js:178:30
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async createBrowserPage (/srv/[redacted]/dist/utilities.js:61:14)
    at async getForeignEvent (/srv/[redacted]/dist/countries/de/[redacted].js:153:18)
    at async Object.scrapeEvent (/srv/[redacted]/dist/countries/de/[redacted].js:241:24)
    at async scrapeEvent (/srv/node_modules/@applaudience/cinema-data-scraper/dist/scrapers.js:68:42)
    at async scrapeData (/srv/dist/routines/executeCinemaDataTask.js:89:18)
    at async runTaskBody (/srv/dist/routines/executeCinemaDataTask.js:378:29)

```

Here is how the connection is handled:

```js
// @flow

import puppeteer from 'puppeteer';
import {
  BROWSER_HEADLESS,
  BROWSER_WEBSOCKET_URL
} from './config';
import Logger from './Logger';

type BrowserRoutineType = (page: any) => Promise<any>;

// eslint-disable-next-line
export const createBrowserPage = async (routine: BrowserRoutineType) => {
  const log = Logger.child({
    namespace: 'createBrowserPage'
  });

  const browser = browser = await puppeteer.connect({
    browserWSEndpoint: BROWSER_WEBSOCKET_URL,
    ignoreHTTPSErrors: true
  });

  let result;

  try {
    const page = await browser.newPage();

    if (global.applaudienceAppendHttpHeaders) {
      await page.setExtraHTTPHeaders(global.applaudienceAppendHttpHeaders);
    }

    page.on('console', (message) => {
      log.trace({
        message: message.text()
      }, 'browser log');
    });

    await page.setRequestInterception(true);

    // @todo Make configurable.
    page.on('request', (interceptedRequest) => {
      if (
        ['stylesheet', 'image', 'font'].includes(interceptedRequest.resourceType()) ||
        interceptedRequest.url().includes('google-analytics.com') ||
        interceptedRequest.url().includes('facebook.net') ||
        interceptedRequest.url().includes('facebook.com') ||
        interceptedRequest.url().includes('googletagmanager.com') ||
        interceptedRequest.url().includes('windows.net')
      ) {
        interceptedRequest.abort();
      } else {
        interceptedRequest.continue();
      }
    });

    result = await routine(page);
  } catch (error) {
    if (BROWSER_HEADLESS) {
      await browser.disconnect();
    } else {
      await browser.close();
    }

    throw error;
  }

  if (BROWSER_HEADLESS) {
    await browser.disconnect();
  } else {
    await browser.close();
  }

  return result;
};

```

Here resource allocation manifest:

```yaml
resources:
  requests:
    memory: '500Mi'
    cpu: '250m'
  limits:
    memory: '1Gi'
    cpu: '1000m'

```

Here is top:

```
browserless-68c589fcf-2vkc4                     971m         289Mi
browserless-68c589fcf-5wpgf                     977m         494Mi
browserless-68c589fcf-66l68                     829m         498Mi
browserless-68c589fcf-6gg2k                     834m         635Mi
browserless-68c589fcf-9qbvm                     936m         567Mi
browserless-68c589fcf-b52qj                     522m         169Mi
browserless-68c589fcf-cdqm2                     718m         542Mi
browserless-68c589fcf-cqvjn                     887m         312Mi
browserless-68c589fcf-dcttg                     529m         492Mi
browserless-68c589fcf-gwzbb                     786m         472Mi
browserless-68c589fcf-jsxn5                     967m         511Mi
browserless-68c589fcf-mqn5z                     240m         316Mi
browserless-68c589fcf-pb9xc                     936m         517Mi
browserless-68c589fcf-pv8l4                     867m         512Mi
browserless-68c589fcf-q2qmp                     782m         473Mi
browserless-68c589fcf-s8gts                     989m         454Mi
browserless-68c589fcf-sfmp9                     754m         342Mi
browserless-68c589fcf-sw9st                     88m          168Mi
browserless-68c589fcf-tm6ll                     820m         344Mi
browserless-68c589fcf-xzcxc                     653m         100Mi

```

Beyond this, don't see much else I can provide to help debug the issue.

**Comment by gajus** [comment]
Couple of observations:

* Unable to replicate this when running one job at a time.
* This is not Puppeteer instructions specific – different scripts fail with the same error.

**Comment by gajus** [comment]
Getting a lot of:

> Error: Navigation failed because browser has disconnected!

**Comment by gajus** [comment]
After I have increased the `CONNECTION_TIMEOUT` to `120000` (2 minutes), then the "Error: Navigation failed because browser has disconnected!" entirely disappeared. However, I have started seeing a lot more:

> TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded

1. Could it be possible that this error is caused by lack of resources (CPU/ memory) assigned to the container?
2. Would this issue be thrown if session is in the queue?, i.e. does navigation timeout include the time that a connection is waiting in the queue?

**Comment by gajus** [comment]
I have done three changes:

* I have increased docker replication count 2x then what I estimate is needed
* I have decreased `MAX_CONCURRENT_SESSIONS` to 3 (previously 5)
* I have decreased `CONNECTION_TIMEOUT` to 3 (previously 10)

After these changes, I never saw again the "Target closed" error:

> Error: Protocol error (Runtime.callFunctionOn): Target closed.

Most of the scripts are executing flawlessly.

After further investigation, the "waiting for selector" issue is specific to a particular script.

> TimeoutError: waiting for selector "#SeatCollection" failed: timeout 30000ms exceeded\

This issue is no longer present either after updating the script (the selector did not exist on some pages).

Based on these experiments, it appears to be purely a resource allocation issue. Hard to say what is the best solution here.

* More logging in Docker container would be definitely helpful.
* Categorizing logs by DEBUG/INFO/WARN/ERROR/CRITICAL would be useful.

**Comment by joelgriffith** [comment]
```Based on these experiments, it appears to be purely a resource allocation issue. Hard to say what is the best solution here.

More logging in Docker container would be definitely helpful.
Categorizing logs by DEBUG/INFO/WARN/ERROR/CRITICAL would be useful.```

Definitely the sentiment I feel. What you're describing is, generally, a resource allocation problem. I'd love to add more logging for the container itself if it's helpful, but not sure what to add that would aide in something like this. Also the `DEBUG/INFO/WARN/ERROR/CRITICAL` is something I've been thinking about as well, not sure if the `debug` module helps in this, but will look into it.

Love your comments though, will definitely add to our docs and look to add more/better logs to our container.

**Comment by gajus** [comment]
> Also the `DEBUG/INFO/WARN/ERROR/CRITICAL` is something I've been thinking about as well, not sure if the `debug` module helps in this, but will look into it.
>
> Love your comments though, will definitely add to our docs and look to add more/better logs to our container.

https://github.com/gajus/roarr

Consider Roarr.

I am still debugging some of these issues. Will add to this thread if I uncover anything particularly useful.

**Comment by gajus** [comment]
One of the neater things I have done, is I uploading tracing files for all failings requests, e.g.

```diff
// @flow

import puppeteer from 'puppeteer';
import got from 'got';
import {
  BROWSER_CLOSE,
  BROWSER_HEADLESS,
  BROWSER_UPLOAD_ERROR_TRACE,
  BROWSER_WEBSOCKET_URL
} from './config';
import Logger from './Logger';

type BrowserRoutineType = (page: any) => Promise<any>;

+export const uploadTrace = async (trace: Buffer): Promise<void> => {
+  const log = Logger.child({
+    namespace: 'createBrowserPage'
+  });
+
+  const response = await got('https://transfer.sh/trace', {
+    body: trace,
+    method: 'put'
+  });
+
+  log.info('trace uploaded %s', response.body.trim());
+};

export const createBrowserPage = async (routine: BrowserRoutineType) => {
  const log = Logger.child({
    namespace: 'createBrowserPage'
  });

  let browser;

  if (BROWSER_HEADLESS) {
    browser = await puppeteer.connect({
      browserWSEndpoint: BROWSER_WEBSOCKET_URL,
      ignoreHTTPSErrors: true
    });
  } else {
    browser = await puppeteer.launch({
      headless: false,
      ignoreHTTPSErrors: true,
      slowMo: 250
    });
  }

  const terminate = async () => {
    if (BROWSER_CLOSE) {
      await browser.close();
    } else {
      await browser.disconnect();
    }
  };

  let page;

  try {
    page = await browser.newPage();

    if (global.applaudienceAppendHttpHeaders) {
      await page.setExtraHTTPHeaders(global.applaudienceAppendHttpHeaders);
    }

    page.on('console', (message) => {
      log.trace({
        message: message.text()
      }, 'browser log');
    });

    await page.setDefaultNavigationTimeout(60 * 1000);
    await page.setDefaultTimeout(30 * 1000);

    await page.setRequestInterception(true);
  } catch (error) {
    log.warn('could not create new browser page');

    await terminate();

    throw error;
  }

  let result;
  let routineError;

  try {
+    await page.tracing.start({
+      screenshots: true
+    });

    result = await routine(page);

+    await page.tracing.stop();
  } catch (error) {
    log.warn('could complete page routine');

    routineError = error;
  }

+  if (BROWSER_UPLOAD_ERROR_TRACE && routineError) {
+    let trace;
+
+    try {
+      trace = await page.tracing.stop();
+    } catch (error) {
+      log.warn('could not obtain trace');
+    }
+
+    if (trace) {
+      try {
+        await uploadTrace(trace);
+      } catch (error) {
+        log.warn('could not upload trace');
+      }
+    }
+  }

  await terminate();

  if (routineError) {
    throw routineError;
  }

  return result;
};

```

This so far is proving extremely useful way of debugging Puppeteer behaviour.

**Comment by joelgriffith** [comment]
Going to close this out since we've found the root issue, however I think better/more logs are going to be a good thing going forward.
