### ISSUE TITLE
Error: net::ERR_BAD_SSL_CLIENT_AUTH_CERT

### ISSUE THREAD

**Issue by typkrft** [browserless/chrome#2557]
**Describe the bug**
I've extended the docker file to install a couple of certificates and a chrome policy to auto accept them. When I run code from the live browserless web console I am able to use them. However when I connect remotely I get `Error: net::ERR_BAD_SSL_CLIENT_AUTH_CERT`.

Dockerfile:
```DOCKERFILE
# Select Base Image
FROM browserless/chrome

# Install Additional Packages for certs
USER root
RUN apt update && apt-get install -yq libnss3-tools

# Force Install Chrome
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN dpkg -i google-chrome-stable_current_amd64.deb

# Install Chrome Policies
RUN mkdir -p /etc/opt/chrome/policies/managed
COPY policy.json /etc/opt/chrome/policies/managed

# Create Cert Database
USER blessuser
RUN mkdir -p /home/blessuser/.pki/nssdb
RUN certutil -d sql:/home/blessuser/.pki/nssdb -N

# Copy Certs to Container
COPY cert_id.pfx /home/blessuser/certs/cert_id.pfx
COPY cert_enc.pfx /home/blessuser/certs/cert_enc.pfx

# Install Certs
RUN pk12util -i /home/blessuser/certs/cert_id.pfx -W "aPassword" -d sql:/home/blessuser/.pki/nssdb
RUN pk12util -i /home/blessuser/certs/cert_enc.pfx -W "aPassword" -d sql:/home/blessuser/.pki/nssdb

# Start Browserless
EXPOSE 3000
CMD ["/usr/src/app/start.sh"]
```

**To Reproduce**
Working:
1. Go to web console - in my case 10.10.10.4:7080
2. Run Code 
```JS
export default async ({ page }: { page: Page }) => {
  await page.goto('https://asite.com/teams/api/oauth/login?loginType=certificate');
    await page.evaluate(() => { debugger; });
};
```
3. Certs are auto selected and show my user to select

Not Working:
1. Create a test.js file with the following code
```JS
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.connect(
        {
            "browserWSEndpoint": "ws://10.10.10.4:7080",
            "ignoreHTTPSErrors": true,
            "headless": false,
            "args": [
                "--ignore-certificate-errors",
                "--ignore-certificate-errors-spki-list",
            ],
        }
    )
    const page = await browser.newPage();
    await page.goto('https://asite.com/teams/api/oauth/login?loginType=certificate')
    await page.screenshot({ path: 'example.png' })

    await browser.close()

})();
```
2. Error
```
/Users/typkrft/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:194
                    ? new Error(`${response.errorText} at ${url}`)
                      ^

Error: net::ERR_BAD_SSL_CLIENT_AUTH_CERT at https://asite.com/teams/api/oauth/login?loginType=certificate
    at navigate (/Users/typkrft/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:194:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FrameManager.navigateFrame (/Users/typkrft/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:170:21)
    at async Frame.goto (/Users/typkrft/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:589:16)
    at async Page.goto (/Users/typkrft/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1089:16)
    at async /Users/typkrft/Code/Git/browserless/test.js:16:5

Node.js v18.3.0
```

**Expected behavior**
Auto Accepts so that I can continue the login process. Or in this specific case take a screenshot

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Browserless Container on Docker version 20.10.17, build 100c701 running on Fedora 36
 - Running Code Remotely from macOS 12.4 (21F79)

**Additional context**
Unfortunately I am unable to provide certs or the exact site.

**Comment by joelgriffith** [comment]
Sadly this an error that Chrome itself throws and not something we have the direct ability to fix

**Comment by typkrft** [comment]
In the case above the likely culprit was that policies weren't being used when connecting remote, maybe because I installed a different version of chrome than what browserless.

Just attempted to resolve this last night and the following setup works. You would need to make sure certutil and pk12util are on your host.

```docker-compose
services:
  browserless:
    container_name: browserless
    image: browserless/chrome:latest
    restart: unless-stopped
    ports:
      - 3002:3000
    environment:
      WORKSPACE_DIR: /downloads
      WORKSPACE_DELETE_EXPIRED: true
      WORKSPACE_EXPIRE_DAYS: 30
      EXIT_ON_HEALTH_FAILURE: true
      DATA_DIR: /session-data
    command: 
      - /bin/bash
      - -c 
      - |
        mkdir -p /home/blessuser/.pki/nssdb 
        /usr/bin/certutil -d "/home/blessuser/.pki/nssdb" -N --empty-password 
        /usr/bin/pk12util -d "/home/blessuser/.pki/nssdb" -i /home/blessuser/certs.pfx -W "aPassword" 
        ./start.sh
    volumes:
      - /usr/bin/pk12util:/usr/bin/pk12util
      - /usr/bin/certutil:/usr/bin/certutil
      - ./storage/certs.pfx:/home/blessuser/certs.pfx
      - ./storage/auto_select_certificate.json:/etc/opt/chrome/policies/managed/auto_select_certificate.json
      - ./storage/session:/session-data
      - ./storage/downloads:/downloads
```
