### ISSUE TITLE
Headless=new causes browser hangups when using DEFAULT_USER_DATA_DIR

### ISSUE THREAD

**Issue by a10kiloham** [browserless/chrome#3178]
**Describe the bug**
When using headless=new and saving the workspace via DEFAULT_USER_DATA_DIR, after around 10 or so requests, it then error until the workspace is deleted. When not using the DEFAULT_USER_DATA_DIR it works fine. Deleting the folder and restarting then lets it run fine until the next hang. Happens regardless of site once it's begun - same error on any page I crawl across various different sites. Restarting the docker image does not solve it - only solution is to rm-rf the cache directory.

**To Reproduce**
Run in docker:
`
!#/bin/bash
BROWSERLESS=browserless/chrome:1-chrome-stable
sudo docker pull $BROWSERLESS
sudo docker run \
-d --name browserless \
--network=mynet \
--log-opt max-size=10m \
-v /etc/timezone:/etc/timezone \
-v /home/me/browserless-cache:/browserless-cache \
-e "DEFAULT_USER_DATA_DIR=/browserless-cache" \
-e 'DEFAULT_LAUNCH_ARGS=["--start-maximized","--window-size=1920,1100","--headless=new","--disable-blink-features=AutomationControlled","--disable-site-isolation-trials", "--deterministic-fetch"]' \
-e "WORKSPACE_DELETE_EXPIRED=true" \
-e "WORKSPACE_EXPIRE_DAYS=7" \
-e "EXIT_ON_HEALTH_FAILURE=true" \
-e "ENABLE_API_GET=true" \
-e "USE_CHROME_STABLE=true" \
-e "ENABLE_CORS=true" \
-e "DEFAULT_STEALTH=true" \
-e "DEFAULT_HEADLESS=new" \
-e "KEEP_ALIVE=true" \
-e "CHROME_REFRESH_TIME=3600000" \
-e "CONNECTION_TIMEOUT=1600000" \
-e "MAX_CONCURRENT_SESSIONS=10" \
-p 127.0.0.1:9222:3000  \
--restart always \
$BROWSERLESS
`

**Expected behavior**
Normal performance

**Screenshots**
`
2023-04-24T14:16:34.171Z browserless:system ProtocolError: Protocol error (Target.setAutoAttach): Target closed.
    at /usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:104:24
    at new Promise (<anonymous>)
    at Connection.send (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:100:16)
    at ChromeTargetManager.initialize (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ChromeTargetManager.js:245:82)
    at CDPBrowser._attach (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Browser.js:156:76)
    at Function._create (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Browser.js:49:23)
    at ChromeLauncher.launch (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:130:53)
    at async PuppeteerExtra.launch (/usr/src/app/node_modules/puppeteer-extra/dist/index.cjs.js:128:25)
    at async Object.launchChrome (/usr/src/app/build/chrome-helper.js:352:27)
    at async PuppeteerProvider.getChrome (/usr/src/app/build/puppeteer-provider.js:443:15) Issue launching Chrome, retrying 1 times.
2023-04-24T14:16:34.172Z browserless:chrome-helper Launching Chrome with args: {
  "args": [
    "--no-sandbox",
    "--enable-logging",
    "--v1=1",
    "--disable-dev-shm-usage",
    "--no-first-run",
    "--start-maximized",
    "--window-size=1920,1100",
    "--headless=new",
    "--disable-blink-features=AutomationControlled",
    "--disable-site-isolation-trials",
    "--deterministic-fetch",
    "--remote-debugging-port=37911",
    "--user-data-dir=/browserless-cache",
    "--remote-debugging-pipe"
  ],
  "blockAds": false,
  "dumpio": false,
  "headless": true,
  "stealth": true,
  "ignoreDefaultArgs": false,
  "ignoreHTTPSErrors": false,
  "pauseOnConnect": false,
  "playwright": false,
  "playwrightVersion": "1.27",
  "userDataDir": "/browserless-cache",
  "meta": {
    "protocol": null,
    "slashes": null,
    "auth": null,
    "host": null,
    "port": null,
    "hostname": null,
    "hash": null,
    "search": null,
    "query": {},
    "pathname": "/",
    "path": "/",
    "href": "/"
  },
  "executablePath": "/usr/bin/google-chrome",
  "handleSIGINT": false,
  "handleSIGTERM": false,
  "handleSIGHUP": false
}
2023-04-24T14:16:34.256Z browserless:system ProtocolError: Protocol error (Target.setAutoAttach): Target closed.
    at /usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:104:24
    at new Promise (<anonymous>)
    at Connection.send (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:100:16)
    at ChromeTargetManager.initialize (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ChromeTargetManager.js:245:82)
    at CDPBrowser._attach (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Browser.js:156:76)
    at Function._create (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Browser.js:49:23)
    at ChromeLauncher.launch (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:130:53)
    at async PuppeteerExtra.launch (/usr/src/app/node_modules/puppeteer-extra/dist/index.cjs.js:128:25)
    at async Object.launchChrome (/usr/src/app/build/chrome-helper.js:352:27)
    at async PuppeteerProvider.getChrome (/usr/src/app/build/puppeteer-provider.js:443:15) Issue launching Chrome, retries exhausted.
2023-04-24T14:16:34.256Z browserless:job ProtocolError: Protocol error (Target.setAutoAttach): Target closed.
    at /usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:104:24
    at new Promise (<anonymous>)
    at Connection.send (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:100:16)
    at ChromeTargetManager.initialize (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ChromeTargetManager.js:245:82)
    at CDPBrowser._attach (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Browser.js:156:76)
    at Function._create (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Browser.js:49:23)
    at ChromeLauncher.launch (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:130:53)
    at async PuppeteerExtra.launch (/usr/src/app/node_modules/puppeteer-extra/dist/index.cjs.js:128:25)
    at async Object.launchChrome (/usr/src/app/build/chrome-helper.js:352:27)
    at async PuppeteerProvider.getChrome (/usr/src/app/build/puppeteer-provider.js:443:15) 2AIVORQ3MIL5FO4TTQFKFV0KICUK87VB: Issue launching Chrome or proxying traffic, failing request
2023-04-24T14:16:34.256Z browserless:server 2AIVORQ3MIL5FO4TTQFKFV0KICUK87VB: Recording failed stat, cleaning up: "Protocol error (Target.setAutoAttach): Target closed."
2023-04-24T14:16:34.256Z browserless:job 2AIVORQ3MIL5FO4TTQFKFV0KICUK87VB: Cleaning up job
2023-04-24T14:16:34.256Z browserless:job 2AIVORQ3MIL5FO4TTQFKFV0KICUK87VB: No browser to cleanup, exiting
2023-04-24T14:16:34.256Z browserless:server Current workload complete.
2023-04-24T14:16:34.257Z browserless:job 2AIVORQ3MIL5FO4TTQFKFV0KICUK87VB: Websocket closed early, removing from queue and closing.
2023-04-24T14:16:34.257Z browserless:job 2AIVORQ3MIL5FO4TTQFKFV0KICUK87VB: Removing job from queue and cleaning up.
2023-04-24T14:16:34.257Z browserless:job 2AIVORQ3MIL5FO4TTQFKFV0KICUK87VB: Cleaning up job
2023-04-24T14:16:34.257Z browserless:job 2AIVORQ3MIL5FO4TTQFKFV0KICUK87VB: No browser to cleanup, exiting
`
in the cache directory, the chrome_debug log has:
`
[21:21:0424/143545.006850:WARNING:chrome_main_delegate.cc(618)] This is Chrome version 111.0.5563.64 (not a warning)
[21:43:0424/143545.028938:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[21:48:0424/143545.115651:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[21:48:0424/143545.115681:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[21:43:0424/143545.116908:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" an
d on UNIX "unix")
[21:43:0424/143545.116941:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" an
d on UNIX "unix")
[21:43:0424/143545.128101:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" an
d on UNIX "unix")
[21:43:0424/143545.128124:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" an
d on UNIX "unix")
[58:58:0424/143545.128555:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
[21:41:0424/143545.130274:WARNING:external_pref_loader.cc(293)] You are using an old-style extension deployment method (external_extensions.json), which will soon be
 deprecated. (see http://developer.chrome.com/extensions/external_extensions.html)
[21:21:0424/143545.133370:WARNING:cursor_loader.cc(123)] Failed to load a platform cursor of type kNull
[21:21:0424/143545.146921:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
[21:95:0424/143545.153596:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[21:95:0424/143545.153622:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[21:95:0424/143545.153646:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[21:95:0424/143545.153650:WARNING:property.cc(144)] DaemonVersion: GetAndBlock: failed.
[21:95:0424/143545.153661:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[21:95:0424/143545.153671:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[87:93:0424/143545.167773:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
`

**Desktop (please complete the following information):**
 - Docker/Ubuntu 22 and 23 - 1:chrome stable and :latest tags all seem to do this. Tried on 4 different machines and it's generally consistent in this behavior when headless=new and DEFAULT 

**Additional context**
Error returned from image is 
`
WebSocket error: socket hang up =========================== logs =========================== <ws connecting> ws://browserless:3000 <ws error> error socket hang up <ws connect error> ws://browserless:3000 socket hang up <ws disconnected> ws://browserless:3000 code=1006 reason= ============================================================
`

**Comment by a10kiloham** [comment]
This site/URL seems to trigger the bug more quickly https://www.zoopla.co.uk/property/uprn/5045766/

**Comment by dgtlmoon** [comment]
Hmm i'm seeing something similar with lots of errors related to " Failed to connect to socket /run/dbus/system_bus_socket" from the container (1.60-chrome)
