### ISSUE TITLE
"Socket hang up" errors when running as standalone container

### ISSUE THREAD

**Issue by pidgezero-one** [browserless/chrome#3476]
**Describe the bug**
All websocket requests to my browserless/chome container are failing with a "Socket hang up" error.

**To Reproduce**

My docker-compose.yml file:
```yaml
version: "3"
services:
  chrome:
    image: browserless/chrome
    platform: linux/amd64
    privileged: true
    ports:
      - 3033:3000
    deploy:
      resources:
        limits:
          memory: 4096M
```

After bringing up the container, when I make a websocket request in Postman to ws://localhost:3033, I receive the error "Could not connect to ws://localhost:3033 Error: socket hang up"

Likewise, a Puppeteer application in a non-containerized application fails upon executing this code (the page it's trying to render is a simple image and two text boxes): 

```javascript
const browser = await connect({ browserWSEndpoint: `ws://localhost:3033` });
```

The error logs in the browserless/chrome container are as follows:

```
2023-08-31T13:30:03.388Z browserless:job 7Z8155FPN9AS9J3QMR37AX2MFYFD7SVC: /: Inbound WebSocket request.
2023-08-31T13:30:03.548Z browserless:hardware Checking overload status: CPU 33% Memory 19%
2023-08-31T13:30:03.562Z browserless:job 7Z8155FPN9AS9J3QMR37AX2MFYFD7SVC: Adding new job to queue.
2023-08-31T13:30:03.567Z browserless:server Starting new job
2023-08-31T13:30:03.569Z browserless:system Generating fresh chrome browser
2023-08-31T13:30:03.581Z browserless:job 7Z8155FPN9AS9J3QMR37AX2MFYFD7SVC: Getting browser.
2023-08-31T13:30:03.595Z browserless:chrome-helper Launching Chrome with args: {
  "args": [
    "--no-sandbox",
    "--enable-logging",
    "--v1=1",
    "--disable-dev-shm-usage",
    "--no-first-run",
    "--remote-debugging-port=39939",
    "--user-data-dir=/tmp/browserless-data-dir-GcqbJi"
  ],
  "blockAds": false,
  "dumpio": false,
  "headless": "new",
  "stealth": false,
  "ignoreDefaultArgs": false,
  "ignoreHTTPSErrors": false,
  "pauseOnConnect": false,
  "playwright": false,
  "userDataDir": "/tmp/browserless-data-dir-GcqbJi",
  "meta": {
    "protocol": null,
    "slashes": null,
    "auth": null,
    "host": null,
    "port": null,
    "hostname": null,
    "hash": null,
    "search": null,
    "query": {},
    "pathname": "/",
    "path": "/",
    "href": "/"
  },
  "executablePath": "/usr/bin/google-chrome",
  "handleSIGINT": false,
  "handleSIGTERM": false,
  "handleSIGHUP": false
}
2023-08-31T13:30:07.913Z browserless:chrome-helper Removing temp data-dir /tmp/browserless-data-dir-GcqbJi
2023-08-31T13:30:07.925Z browserless:system TargetCloseError: Protocol error (Target.setAutoAttach): Target closed
    at CallbackRegistry.clear (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:138:36)
    at #onClose (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:282:25)
    at WebSocket.<anonymous> (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/NodeWebSocketTransport.js:59:30)
    at callListener (/usr/src/app/node_modules/puppeteer-core/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onClose (/usr/src/app/node_modules/puppeteer-core/node_modules/ws/lib/event-target.js:220:9)
    at WebSocket.emit (node:events:513:28)
    at WebSocket.emitClose (/usr/src/app/node_modules/puppeteer-core/node_modules/ws/lib/websocket.js:258:10)
    at Socket.socketOnClose (/usr/src/app/node_modules/puppeteer-core/node_modules/ws/lib/websocket.js:1264:15)
    at Socket.emit (node:events:513:28)
    at TCP.<anonymous> (node:net:313:12) Issue launching Chrome, retrying 1 times.
2023-08-31T13:30:07.937Z browserless:chrome-helper Launching Chrome with args: {
  "args": [
    "--no-sandbox",
    "--enable-logging",
    "--v1=1",
    "--disable-dev-shm-usage",
    "--no-first-run",
    "--remote-debugging-port=40141",
    "--user-data-dir=/tmp/browserless-data-dir-2tfFhH"
  ],
  "blockAds": false,
  "dumpio": false,
  "headless": "new",
  "stealth": false,
  "ignoreDefaultArgs": false,
  "ignoreHTTPSErrors": false,
  "pauseOnConnect": false,
  "playwright": false,
  "userDataDir": "/tmp/browserless-data-dir-2tfFhH",
  "meta": {
    "protocol": null,
    "slashes": null,
    "auth": null,
    "host": null,
    "port": null,
    "hostname": null,
    "hash": null,
    "search": null,
    "query": {},
    "pathname": "/",
    "path": "/",
    "href": "/"
  },
  "executablePath": "/usr/bin/google-chrome",
  "handleSIGINT": false,
  "handleSIGTERM": false,
  "handleSIGHUP": false
}
2023-08-31T13:30:08.553Z browserless:chrome-helper Temp dir /tmp/browserless-data-dir-GcqbJi removed successfully
2023-08-31T13:30:11.239Z browserless:chrome-helper Removing temp data-dir /tmp/browserless-data-dir-2tfFhH
2023-08-31T13:30:11.248Z browserless:system TargetCloseError: Protocol error (Target.setAutoAttach): Target closed
    at CallbackRegistry.clear (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:138:36)
    at #onClose (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:282:25)
    at WebSocket.<anonymous> (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/NodeWebSocketTransport.js:59:30)
    at callListener (/usr/src/app/node_modules/puppeteer-core/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onClose (/usr/src/app/node_modules/puppeteer-core/node_modules/ws/lib/event-target.js:220:9)
    at WebSocket.emit (node:events:513:28)
    at WebSocket.emitClose (/usr/src/app/node_modules/puppeteer-core/node_modules/ws/lib/websocket.js:258:10)
    at Socket.socketOnClose (/usr/src/app/node_modules/puppeteer-core/node_modules/ws/lib/websocket.js:1264:15)
    at Socket.emit (node:events:513:28)
    at TCP.<anonymous> (node:net:313:12) Issue launching Chrome, retries exhausted.
2023-08-31T13:30:11.249Z browserless:job TargetCloseError: Protocol error (Target.setAutoAttach): Target closed
    at CallbackRegistry.clear (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:138:36)
    at #onClose (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:282:25)
    at WebSocket.<anonymous> (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/NodeWebSocketTransport.js:59:30)
    at callListener (/usr/src/app/node_modules/puppeteer-core/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onClose (/usr/src/app/node_modules/puppeteer-core/node_modules/ws/lib/event-target.js:220:9)
    at WebSocket.emit (node:events:513:28)
    at WebSocket.emitClose (/usr/src/app/node_modules/puppeteer-core/node_modules/ws/lib/websocket.js:258:10)
    at Socket.socketOnClose (/usr/src/app/node_modules/puppeteer-core/node_modules/ws/lib/websocket.js:1264:15)
    at Socket.emit (node:events:513:28)
    at TCP.<anonymous> (node:net:313:12) 7Z8155FPN9AS9J3QMR37AX2MFYFD7SVC: Issue launching Chrome or proxying traffic, failing request
2023-08-31T13:30:11.255Z browserless:server 7Z8155FPN9AS9J3QMR37AX2MFYFD7SVC: Recording failed stat, cleaning up: "Protocol error (Target.setAutoAttach): Target closed"
2023-08-31T13:30:11.263Z browserless:job 7Z8155FPN9AS9J3QMR37AX2MFYFD7SVC: Cleaning up job
2023-08-31T13:30:11.263Z browserless:job 7Z8155FPN9AS9J3QMR37AX2MFYFD7SVC: No browser to cleanup, exiting
2023-08-31T13:30:11.265Z browserless:server Current workload complete.
2023-08-31T13:30:11.297Z browserless:job 7Z8155FPN9AS9J3QMR37AX2MFYFD7SVC: Websocket closed early, removing from queue and closing.
2023-08-31T13:30:11.298Z browserless:job 7Z8155FPN9AS9J3QMR37AX2MFYFD7SVC: Removing job from queue and cleaning up.
2023-08-31T13:30:11.298Z browserless:job 7Z8155FPN9AS9J3QMR37AX2MFYFD7SVC: Cleaning up job
2023-08-31T13:30:11.298Z browserless:job 7Z8155FPN9AS9J3QMR37AX2MFYFD7SVC: No browser to cleanup, exiting
2023-08-31T13:30:11.394Z browserless:chrome-helper Temp dir /tmp/browserless-data-dir-2tfFhH removed successfully
```

Navigating to localhost:3033 in a browser works as expected, it's just the websocket having issues.

**Expected behavior**
I would just expect neither of these requests to fail.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ventura 13.1 (M1 chip)
 - Browser: Chrome
 - Version: Unsure, it's whatever version the `browserless/chrome` image currently points to

**Additional context**
I think I read that ARM64 hosts have complications, but I'm specifying amd64 as my platform for the Docker container because it matches the production environment.

**Comment by andyMrtnzP** [comment]
Sorry for the delay. Yeah, M1 (and ARM in general) has gave us lots of problems. We do deploy a version for arm64. Can you try setting that on the `platform` instead?
