### ISSUE TITLE
Connection to browserless with Taiko

### ISSUE THREAD

**Issue by GautierT** [browserless/chrome#396]
Hi,
I have a docker browserless image running on a remote server.
It's working great, i can access to the online debugger and execute code from the webconsole.

Now, i want to connect to it with [Taiko](https://github.com/getgauge/taiko). 

Following the Taiko doc i set the settings like this : 
```
await openBrowser({
      host: `remote_url.domain_name.com`,
      port: 3000,
})
```
The server seems to respond correctly to the request for a websocket url : 
```
{ description: '',
  devtoolsFrontendUrl:
   '/devtools/inspector.html?ws=ip_address_of_my_server:3000/devtools/page/nCWSVaba',
  targetId: '/devtools/page/nCWSVaba',
  title: 'about:blank',
  type: 'page',
  url: 'about:blank',
  webSocketDebuggerUrl: 'ws://ip_address_of_my_server:3000/devtools/page/nCWSVaba' }
```
But then it throw a 404 : 
```
Error: Unexpected server response: 404
    at ClientRequest.req.on (/Users/me/Documents/Projets/repo/node_modules/ws/lib/websocket.js:595:7)
    at ClientRequest.emit (events.js:189:13)
    at ClientRequest.EventEmitter.emit (domain.js:441:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at Socket.socketOnData (_http_client.js:442:20)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
```

When i `docker logs -f browserless` i can see this : 
```
2019-10-15T13:41:24.606Z browserless:job uMuy8cS6: /devtools/page/nCWSVaba: Inbound WebSocket request.
2019-10-15T13:41:24.607Z browserless:server /devtools/page/nCWSVaba: Couldn't load session for /devtools/page/nCWSVaba
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
Is this a problem with Taiko or with browserless ? Is this related to nginx ?
Thanks !

**Comment by joelgriffith** [comment]
This should be on latest. @GautierT care to give it a spin?
