### ISSUE TITLE
Running out of memory

### ISSUE THREAD

**Issue by Vizzr** [browserless/chrome#441]
Hi,

We use Puppeteer to connect to a Browserless/Chrome docker.
In one of our tries, we wanted to download 769 pages as PDF.
While running this process, we received an error from Puppeteer.

On further investigation, we looked into the Browserless/Chrome docker.
The following logs were given:
```
2019-11-12T10:47:37.079Z browserless:chrome-helper Chrome PID: 25
2019-11-12T10:47:37.756Z browserless:system Chrome launched 3372ms
2019-11-12T10:47:37.757Z browserless:job 8F7C3T4V5EIJ927YH78V6W429AMDS89T: Starting session.
2019-11-12T10:47:37.757Z browserless:job 8F7C3T4V5EIJ927YH78V6W429AMDS89T: Proxying request to /devtools/browser route: ws://127.0.0.1:39035/devtools/browser/53f4af6f-9599-4f0c-a8c9-97484f0bbce3.
internal/child_process.js:394
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:394:11)
    at spawn (child_process.js:540:9)
    at Object.execFile (child_process.js:224:17)
    at exec (child_process.js:145:25)
    at /usr/src/app/node_modules/systeminformation/lib/memory.js:128:9
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  errno: 'ENOMEM',
  code: 'ENOMEM',
  syscall: 'spawn'
}

```

As you can see, we get the error: "Error: spawn ENOMEM".

What can we do about this error?

**Comment by joelgriffith** [comment]
That's an interesting find, looks like it's coming from `systeminformation` which does probe to see how much memory is available.

Do the sessions still run or are they failing? `769` pages as a PDF is very very big, what size machine are you using?

**Comment by Vizzr** [comment]
Thank you for replying so quickly to my issue.

It is indeed a very very big PDF. It doesn't happen that often that clients will print this out, but we wanted to test how much and fast Puppeteer <-> Browserless/Chrome was.

The machine has 4GB of memory, but there are also running other Docker containers.

The browserless/Chrome Docker crashes and restarts when the Error happens:

````
2019-11-13T06:24:42.239Z browserless:chrome-helper Chrome PID: 485
2019-11-13T06:24:43.303Z browserless:system Chrome launched 7274ms
2019-11-13T06:24:43.307Z browserless:job QJNR3KPA73E0HO770JXMTGCJQ82CEK5Q: Starting session.
2019-11-13T06:24:43.307Z browserless:job QJNR3KPA73E0HO770JXMTGCJQ82CEK5Q: Proxying request to /devtools/browser route: ws://127.0.0.1:43747/devtools/browser/c8469f9e-c09e-4990-a8a0-5ffd7f415cf5.
internal/child_process.js:394
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:394:11)
    at spawn (child_process.js:540:9)
    at Object.execFile (child_process.js:224:17)
    at exec (child_process.js:145:25)
    at /usr/src/app/node_modules/systeminformation/lib/memory.js:128:9
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  errno: 'ENOMEM',
  code: 'ENOMEM',
  syscall: 'spawn'
}
2019-11-13T06:33:11.926Z browserless:server {
  CONNECTION_TIMEOUT: 600000,
  MAX_CONCURRENT_SESSIONS: 10,
  QUEUE_LENGTH: 10,
  SINGLE_RUN: false,
  CHROME_REFRESH_TIME: 1800000,
  KEEP_ALIVE: false,
  DEFAULT_BLOCK_ADS: false,
  DEFAULT_HEADLESS: true,
  DEFAULT_LAUNCH_ARGS: [],
  DEFAULT_IGNORE_DEFAULT_ARGS: false,
  DEFAULT_IGNORE_HTTPS_ERRORS: false,
  DEFAULT_USER_DATA_DIR: undefined,
  PREBOOT_CHROME: false,
  CHROME_BINARY_LOCATION: '/usr/bin/google-chrome',
  DEBUG: 'browserless*',
  DEMO_MODE: false,
  DISABLED_FEATURES: [],
  ENABLE_CORS: false,
  ENABLE_XVBF: true,
  TOKEN: null,
  DISABLE_AUTO_SET_DOWNLOAD_BEHAVIOR: false,
  FUNCTION_BUILT_INS: [ 'url' ],
  FUNCTION_ENABLE_INCOGNITO_MODE: false,
  FUNCTION_EXTERNALS: [ 'lighthouse', 'node-pdftk' ],
  WORKSPACE_DIR: '/usr/src/app/workspace',
  WORKSPACE_DELETE_EXPIRED: false,
  WORKSPACE_EXPIRE_DAYS: 30,
  FAILED_HEALTH_URL: null,
  QUEUE_ALERT_URL: null,
  REJECT_ALERT_URL: null,
  TIMEOUT_ALERT_URL: null,
  ERROR_ALERT_URL: null,
  EXIT_ON_HEALTH_FAILURE: false,
  MAX_CPU_PERCENT: 99,
  MAX_MEMORY_PERCENT: 99,
  METRICS_JSON_PATH: null,
  HOST: '0.0.0.0',
  MAX_PAYLOAD_SIZE: '5mb',
  PORT: 3000
} Final configuration
```

The weird thing is that our Printing service, that uses Puppeteer to call Browserless/Chrome, already crashes after about a minute or 2 with the following error:

```
{ Error: Protocol error (Page.printToPDF): Target closed.
    at Promise (/usr/src/app/node_modules/puppeteer-core/lib/Connection.js:183:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/usr/src/app/node_modules/puppeteer-core/lib/Connection.js:182:12)
    at Page.pdf (/usr/src/app/node_modules/puppeteer-core/lib/Page.js:926:39)
    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer-core/lib/helper.js:112:23)
    at Object.<anonymous> (/usr/src/app/dist/models/PdfPrinter.js:40:47)
    at step (/usr/src/app/node_modules/tslib/tslib.js:133:27)
    at Object.next (/usr/src/app/node_modules/tslib/tslib.js:114:57)
    at fulfilled (/usr/src/app/node_modules/tslib/tslib.js:104:62)
    at process._tickCallback (internal/process/next_tick.js:68:7) message: 'Protocol error (Page.printToPDF): Target closed.' }
```

After that the Browserless/Chrome is still running without any error. Session is also still up. Then after almost 10 minutes, it threw the ENOMEM error and then restarted.

The Connection timeout to the Browserless/Chrome is 10 minutes (600000). Maybe that could be something?
I looked at the logs and the last time (when I made this post) the Docker also restarted after ~ 10 minutes.

**Comment by joelgriffith** [comment]
So after some digging it looks like our hardware monitoring code is what is causing this issue. I think the Target closed problem is still likely due to resource constraints, but the restart is from us not catching the resource check properly.

I’ll try and get a PR for that whipped up

**Comment by joelgriffith** [comment]
Fixed in https://github.com/browserless/chrome/pull/454. Note that this only fixes the reboot problem, your memory/sluggishness might just be due to hardware constraints

**Comment by Vizzr** [comment]
Thanks for investigating the issue.

I'll talk to the infrastructure guys overhere to see if they can increase our memory.

**Comment by alikhil** [comment]
I had the same problem, and I've solved it by configuring swap space according to [this answer in SO](https://stackoverflow.com/a/32444643/3443964)
