### ISSUE TITLE
Can't use  [fileChooser]

### ISSUE THREAD

**Issue by julie0420** [browserless/chrome#453]
I am getting an error when trying to use [fileChooser] to upload an image. 
This is my code:
```
const puppeteer = require('puppeteer');
async function getTest() {
    const browser = await puppeteer.connect({
      browserWSEndpoint: 'wss://chrome.browserless.io'
    });
    const page = (await browser.pages())[0];
    await page.goto('https://someWebSite.com');
    const title = await page.title();

    //do stuff

    console.log("before uploading photo");  //my code gets to here

    const [fileChooser] = await Promise.all([page.waitForFileChooser(),page.click('#uploadTrigger'),]); //**this is where I get an error**
    await fileChooser.accept(['C:\\myProgram\\pic.jpg']);
    await page.click('#edit-submit');   
  }
 getTest().then(console.log);
```

This is the error I get:
puppeteer-web.js:15515 Uncaught (in promise) Error: File chooser handling does not work with multiple connections to the same page
    at Page.waitForFileChooser (puppeteer-web.js:15515)
    at Page.<anonymous> (puppeteer-web.js:17777)
    at getTest (jsFunction.js:40)

**Comment by joelgriffith** [comment]
Fixed in https://github.com/browserless/chrome/pull/454

**Comment by melalj** [comment]
I'm having a similar error while using the latest image of browserless: `browserless/chrome:1.22-puppeteer-2.0.0`

This is the code I'm using:
```js
    const [fileChooser] = await Promise.all([
      page.waitForFileChooser(),
      page.click('label[for=upload_img]'),
    ]);
    await fileChooser.accept(['/tmp/img.jpg]);
```

I'm getting the following error:
```
File chooser handling does not work with multiple connections to the same page | stack: Error: File chooser handling does not work with multiple connections to the same page
at Page.waitForFileChooser (/app/node_modules/puppeteer-core/lib/Page.js:167:13)
at Page.<anonymous> (/app/node_modules/puppeteer-core/lib/helper.js:112:23)
```
