### ISSUE TITLE
Nodejs: Session closed when running defiant.search a second time

### ISSUE THREAD

**Issue by mapi33** [browserless/chrome#469]
I've got the following function in nodejs (for test purpose)

```
const defiant =  require('defiant.js');

const json = {"coord":{"lon":-0.13,"lat":51.51},"weather":[{"id":300,"main":"Drizzle","description":"light intensity drizzle","icon":"09d"}]}

const evaluateJSON = async (jsonStr, xPath) => {

    let res = await defiant.search(JSON.parse(jsonStr), xPath)
    console.log("res", res);

    let res2 = await defiant.search(JSON.parse(jsonStr), xPath)      // ==>throws error
    console.log("res2", res2);

    return res
}

evaluateJSON(JSON.stringify(json), "//*")
```

the first search works well!
the second search triggers an error

```
node:12845) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at Promise (/var/www/api/node_modules/puppeteer/lib/Connection.js:183:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/var/www/api/node_modules/puppeteer/lib/Connection.js:182:12)
    at ExecutionContext._evaluateInternal (/var/www/api/node_modules/puppeteer/lib/ExecutionContext.js:107:44)
    at ExecutionContext.evaluate (/var/www/api/node_modules/puppeteer/lib/ExecutionContext.js:48:23)
    at ExecutionContext.<anonymous> (/var/www/api/node_modules/puppeteer/lib/helper.js:112:23)
    at DOMWorld.evaluate (/var/www/api/node_modules/puppeteer/lib/DOMWorld.js:112:20)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
  -- ASYNC --
    at Frame.<anonymous> (/var/www/api/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.evaluate (/var/www/api/node_modules/puppeteer/lib/Page.js:833:43)
    at Page.<anonymous> (/var/www/api/node_modules/puppeteer/lib/helper.js:112:23)
    at Object.search (/var/www/api/node_modules/defiant.js/index.js:67:37)
    at evaluateJSON (/var/www/api/src/tests/defiant.js:10:30)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
````

I run defiant.js v 2.2.6
Node v11.10.0

**Comment by joelgriffith** [comment]
Sorry for the delay! I'm not familiar with defiant, are you able to connect it over to browserless somehow? I'm not seeing that in their documentation...

**Comment by mapi33** [comment]
Hi, 
That's a complete mistake. that post was for defiant not for Browserless. No idea how it got there!
Sorry about that!
