### ISSUE TITLE
Docker image browserless/chrome:1-puppeteer-1.17.0 does not work correctly with puppeteer-1.17.0

### ISSUE THREAD

**Issue by benjhess** [browserless/chrome#486]
Should be 1.17.0 but is 2.2.0:
```
docker inspect browserless/chrome:1-puppeteer-1.17.0 | grep puppeteerVersion
"puppeteerVersion": "2.0.0",
```

Using puppeteer 1.17.0 with browserless:
```

browserless_1  | 2019-12-20T19:57:09.800Z browserless:job UFPWZVN6ZRQHVFTIK7HN8B1BX1S0QJ8J: Proxying request to /devtools/browser route: ws://127.0.0.1:46563/devtools/browser/0a26207e-1f85-4e00-8b6f-67cd3386ce24.
browserless_1  | Unhandled Rejection at: Promise {
browserless_1  |   <rejected> Error: Protocol error (Page.setInterceptFileChooserDialog): 'Page.setInterceptFileChooserDialog' wasn't found
browserless_1  |       at /usr/src/app/node_modules/puppeteer/lib/Connection.js:183:56
browserless_1  |       at new Promise (<anonymous>)
browserless_1  |       at CDPSession.send (/usr/src/app/node_modules/puppeteer/lib/Connection.js:182:12)
browserless_1  |       at setupPage (/usr/src/app/build/chrome-helper.js:23:12)
browserless_1  |       at processTicksAndRejections (internal/process/task_queues.js:93:5) {
browserless_1  |     message: "Protocol error (Page.setInterceptFileChooserDialog): 'Page.setInterceptFileChooserDialog' wasn't found"
browserless_1  |   }
```

**Comment by joelgriffith** [comment]
I think there’s a bug in how we’re labeling images, so thanks for pointing out. That later issue is a bit more concerning, and I’ll investigate!

**Comment by joelgriffith** [comment]
Doing:

```
$ docker run \
  --rm \
  -p 3000:3000 \
  -e "CONNECTION_TIMEOUT=120000" \
  -e "MAX_CONCURRENT_SESSIONS=10" \
  -e "MAX_QUEUE_LENGTH=20" \
  -e "FUNCTION_EXTERNALS=[\"fetch\",\"querystring\",\"url\",\"request\"]" \
  browserless/chrome:1-puppeteer-1.17.0
```

Then:
```
$ docker exec -it -u root CONTAINER_ID bash
```

Finally:
```
root@CONTAINER:/usr/src/app/node_modules/puppeteer# cat package.json | grep version
    "type": "version",
    "apply-next-version": "node utils/apply_next_version.js",
  "version": "1.17.0"
```
