### ISSUE TITLE
Does not work with puppeteer 2.1.0 

### ISSUE THREAD

**Issue by gajus** [browserless/chrome#548]
Simply connecting to the browser and creating a page gives error:

```
(node:14196) UnhandledPromiseRejectionWarning: Error: Protocol error (Page.setInterceptFileChooserDialog): Cannot enable file chooser interception because other protocol client already intercepts it

```

**Comment by gajus** [comment]
Browserless reports:

```
browserless:chrome-helper Error setting up new browser Error: Protocol error (Emulation.setDeviceMetricsOverride): Session closed. Most likely the page has been closed.
    at CDPSession.send (/usr/src/app/node_modules/puppeteer/lib/Connection.js:180:29)
    at EmulationManager.emulateViewport (/usr/src/app/node_modules/puppeteer/lib/EmulationManager.js:41:20)
    at Page.setViewport (/usr/src/app/node_modules/puppeteer/lib/Page.js:844:54)
    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:112:23)
    at Function.create (/usr/src/app/node_modules/puppeteer/lib/Page.js:50:18)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Browser.<anonymous> (/usr/src/app/build/chrome-helper.js:67:26)
  -- ASYNC --
    at Target.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:111:15)
    at Browser.<anonymous> (/usr/src/app/build/chrome-helper.js:67:39)
    at Browser.emit (events.js:223:5)
    at Browser._targetCreated (/usr/src/app/node_modules/puppeteer/lib/Browser.js:121:12)
    at processTicksAndRejections (internal/process/task_queues.js:94:5) +11ms

```

**Comment by joelgriffith** [comment]
Thanks for the reporting, seeing that in the PR here: https://github.com/browserless/chrome/pull/541. Will take a look shortly!

**Comment by joelgriffith** [comment]
I’ve gotten a build with 2.1.0 up, likely on latest, however it was quite a bit of mechanical work since the rev that 2.1.0 ships with wasn’t super stable.

I haven’t put it through yet our stress test just yet, but will soon

**Comment by joelgriffith** [comment]
Should be fixed now
