### ISSUE TITLE
page crash on requests - puppeteer and browserless

### ISSUE THREAD

**Issue by nicolaskoopol** [browserless/chrome#552]
Hello guys,

We are facing problems for a few hours using puppeteer (2.0 or 2.1) with our browserless.io accounts. We have tested several and even using a new one.

The following code works in try-puppeteer but leads to a page crash using browserless.io.

```
const browser = await puppeteer.launch();
const page = await browser.newPage();

let url ='https://www.technikdirekt.de/smartphone-navi/wearables/fitness-armband/490114/fitbit-charge-3-graphit/schwarz'
await page.goto(url)
   let sel = ''
    sel = 'h1'
    try{
        await page.waitForSelector(sel, { timeout: 30000 })
       console.log('h1 found')
    } catch(e) {
        console.log('timeout for searching h1 ' + url)
    }

    sel = '.price--content'
    try{
        await page.waitForSelector(sel, { timeout: 30000 })
       console.log('price found')
    } catch(e) {
        console.log('timeout for searching price ' + url)
    }

await browser.close();

```

The code is deployed on a google cloud function and crashes at
`await page.goto(url)`

Stacktrace:
`
Page crashed! at Page._onTargetCrashed (/srv/functions/node_modules/puppeteer-core/lib/Page.js:211:24) at CDPSession.Page.client.on.event (/srv/functions/node_modules/puppeteer-core/lib/Page.js:122:56) at CDPSession.emit (events.js:198:13) at CDPSession.EventEmitter.emit (domain.js:466:23) at CDPSession._onMessage (/srv/functions/node_modules/puppeteer-core/lib/Connection.js:200:12) at Connection._onMessage (/srv/functions/node_modules/puppeteer-core/lib/Connection.js:112:17) at WebSocketTransport._ws.addEventListener.event (/srv/functions/node_modules/puppeteer-core/lib/WebSocketTransport.js:44:24) at WebSocket.onMessage (/srv/functions/node_modules/ws/lib/event-target.js:120:16) at WebSocket.emit (events.js:198:13) at WebSocket.EventEmitter.emit (domain.js:466:23)`

It was working great yesterday. We are facing this on several (almost all) websites and urls.

Wouldn't there be something on your side?
Is there anything we can check on our side?

Thanks in advance

Nicolas

**Comment by nicolaskoopol** [comment]
Not worth mentionning that we did find a workaround. It seems that the parameter ignoreDefaults=false is not correctly managed and leads to strange behaviour.

Without it, we got back to a normal situation.

Not that the page crash is not triggered as a proper exception. So not possible to catch it and release ressources (browser.close) and therefore generates ressources expenses...
