### ISSUE TITLE
Browserless stuck after ~20 pdf creations

### ISSUE THREAD

**Issue by POLAK93** [browserless/chrome#572]
I use browserless with pupetter to generate pdf from html on backend side.
And after around ~20 generation browserless logs (see below) and stuck. 
After restart (docker container) all going back to normal.
```
    at Frame.goto (/usr/src/app/node_modules/puppeteer/lib/FrameManager.js:407:37),
    at Frame.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:112:23),
    at Page.goto (/usr/src/app/node_modules/puppeteer/lib/Page.js:629:49),
    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:112:23),
    at PuppeteerProvider.cleanUpJob (/usr/src/app/build/puppeteer-provider.js:382:23),
  -- ASYNC --,
    at Frame.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:111:15),
    at Page.goto (/usr/src/app/node_modules/puppeteer/lib/Page.js:629:49),
    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:112:23),
    at PuppeteerProvider.cleanUpJob (/usr/src/app/build/puppeteer-provider.js:382:23),
    at runMicrotasks (<anonymous>),
    at processTicksAndRejections (internal/process/task_queues.js:94:5) {,
  message: 'Protocol error (Page.navigate): Target closed.',
},
2020-02-10T21:49:05.973Z browserless:chrome-helper Browser process exited with code 0 and signal null, cleaning up,
2020-02-10T21:49:05.974Z browserless:chrome-helper Shutting down browser with close command,
2020-02-10T21:49:05.974Z browserless:chrome-helper Removing temp data-dir /tmp/browserless-data-dir-fp6zOy,
2020-02-10T21:49:05.975Z browserless:chrome-helper Sending SIGKILL signal to browser process 37,
2020-02-10T21:49:09.469Z browserless:job 56SMITQIKN6NDMO93HD1XNGKOIU0PIMH: /: Inbound WebSocket request.,
2020-02-10T21:49:09.470Z browserless:job 56SMITQIKN6NDMO93HD1XNGKOIU0PIMH: Adding new job to queue.,
2020-02-10T21:49:09.470Z browserless:job 56SMITQIKN6NDMO93HD1XNGKOIU0PIMH: Getting browser.,
2020-02-10T21:49:09.470Z browserless:system Using pre-booted chrome: true,
2020-02-10T21:49:09.470Z browserless:job 56SMITQIKN6NDMO93HD1XNGKOIU0PIMH: Starting session.,
2020-02-10T21:49:09.471Z browserless:job 56SMITQIKN6NDMO93HD1XNGKOIU0PIMH: Proxying request to /devtools/browser route: ws://127.0.0.1:44625/devtools/browser/18059d64-eb56-416f-a122-617cffb9a400.,
2020-02-10T21:49:09.473Z browserless:server Issue communicating with Chrome: "connect ECONNREFUSED 127.0.0.1:44625",
2020-02-10T21:49:09.477Z browserless:server 56SMITQIKN6NDMO93HD1XNGKOIU0PIMH: Recording successful stat and cleaning up.,
2020-02-10T21:49:09.477Z browserless:job 56SMITQIKN6NDMO93HD1XNGKOIU0PIMH: Cleaning up job,
2020-02-10T21:49:09.478Z browserless:job 56SMITQIKN6NDMO93HD1XNGKOIU0PIMH: Browser has been alive for 400964ms,
2020-02-10T21:49:09.478Z browserless:job 56SMITQIKN6NDMO93HD1XNGKOIU0PIMH: Pushing browser back into swarm, clearing pages,
2020-02-10T21:49:09.478Z browserless:server Current workload complete.,
Unhandled Rejection at: Promise {,
  <rejected> TypeError: Cannot read property 'goto' of undefined,
      at PuppeteerProvider.cleanUpJob (/usr/src/app/build/puppeteer-provider.js:382:23),
      at runMicrotasks (<anonymous>),
      at processTicksAndRejections (internal/process/task_queues.js:94:5),
} reason: TypeError: Cannot read property 'goto' of undefined,
    at PuppeteerProvider.cleanUpJob (/usr/src/app/build/puppeteer-provider.js:382:23),
    at runMicrotasks (<anonymous>),
    at processTicksAndRejections (internal/process/task_queues.js:94:5),
2020-02-10T21:49:14.082Z browserless:job 9O07Z6QCEEX2ARIYPFW6IP92ZDQKG0KJ: /: Inbound WebSocket request.,
2020-02-10T21:49:14.083Z browserless:job 9O07Z6QCEEX2ARIYPFW6IP92ZDQKG0KJ: Adding new job to queue.,
2020-02-10T21:49:14.083Z browserless:job 9O07Z6QCEEX2ARIYPFW6IP92ZDQKG0KJ: Getting browser.,
2020-02-10T21:49:14.084Z browserless:system Using pre-booted chrome: true,
2020-02-10T21:49:14.084Z browserless:job 9O07Z6QCEEX2ARIYPFW6IP92ZDQKG0KJ: Starting session.,
2020-02-10T21:49:14.084Z browserless:job 9O07Z6QCEEX2ARIYPFW6IP92ZDQKG0KJ: Proxying request to /devtools/browser route: ws://127.0.0.1:33135/devtools/browser/97e3fb8f-64d3-4cab-9378-1b79093828c9.,
2020-02-10T21:49:14.085Z browserless:server Issue communicating with Chrome: "connect ECONNREFUSED 127.0.0.1:33135",
2020-02-10T21:49:14.086Z browserless:server 9O07Z6QCEEX2ARIYPFW6IP92ZDQKG0KJ: Recording successful stat and cleaning up.,
2020-02-10T21:49:14.086Z browserless:job 9O07Z6QCEEX2ARIYPFW6IP92ZDQKG0KJ: Cleaning up job,
2020-02-10T21:49:14.086Z browserless:job 9O07Z6QCEEX2ARIYPFW6IP92ZDQKG0KJ: Browser has been alive for 404849ms,
2020-02-10T21:49:14.087Z browserless:job 9O07Z6QCEEX2ARIYPFW6IP92ZDQKG0KJ: Pushing browser back into swarm, clearing pages,
2020-02-10T21:49:14.087Z browserless:server Current workload complete.,
Unhandled Rejection at: Promise {,
  <rejected> TypeError: Cannot read property 'goto' of undefined,
      at PuppeteerProvider.cleanUpJob (/usr/src/app/build/puppeteer-provider.js:382:23),
      at runMicrotasks (<anonymous>),
      at processTicksAndRejections (internal/process/task_queues.js:94:5),
} reason: TypeError: Cannot read property 'goto' of undefined,
    at PuppeteerProvider.cleanUpJob (/usr/src/app/build/puppeteer-provider.js:382:23),
    at runMicrotasks (<anonymous>),
    at processTicksAndRejections (internal/process/task_queues.js:94:5),
2020-02-10T21:49:52.690Z browserless:job R4B0D2N44533YSEVJ9S6GHKN19JINLMF: /: Inbound WebSocket request.,
2020-02-10T21:49:52.690Z browserless:job R4B0D2N44533YSEVJ9S6GHKN19JINLMF: Adding new job to queue.,
2020-02-10T21:49:52.691Z browserless:job R4B0D2N44533YSEVJ9S6GHKN19JINLMF: Getting browser.,
2020-02-10T21:49:52.691Z browserless:system Using pre-booted chrome: true,
2020-02-10T21:49:52.691Z browserless:job R4B0D2N44533YSEVJ9S6GHKN19JINLMF: Starting session.,
2020-02-10T21:49:52.691Z browserless:job R4B0D2N44533YSEVJ9S6GHKN19JINLMF: Proxying request to /devtools/browser route: ws://127.0.0.1:43615/devtools/browser/3f0cfffa-d7f3-4fcc-83d0-d7877cd40687.,
2020-02-10T21:49:52.692Z browserless:server Issue communicating with Chrome: "connect ECONNREFUSED 127.0.0.1:43615",
2020-02-10T21:49:52.693Z browserless:server R4B0D2N44533YSEVJ9S6GHKN19JINLMF: Recording successful stat and cleaning up.,
2020-02-10T21:49:52.693Z browserless:job R4B0D2N44533YSEVJ9S6GHKN19JINLMF: Cleaning up job,
2020-02-10T21:49:52.693Z browserless:job R4B0D2N44533YSEVJ9S6GHKN19JINLMF: Browser has been alive for 443399ms,
2020-02-10T21:49:52.694Z browserless:job R4B0D2N44533YSEVJ9S6GHKN19JINLMF: Pushing browser back into swarm, clearing pages,
2020-02-10T21:49:52.694Z browserless:server Current workload complete.,
Unhandled Rejection at: Promise {,
  <rejected> TypeError: Cannot read property 'goto' of undefined,
      at PuppeteerProvider.cleanUpJob (/usr/src/app/build/puppeteer-provider.js:382:23),
      at runMicrotasks (<anonymous>),
      at processTicksAndRejections (internal/process/task_queues.js:94:5),
} reason: TypeError: Cannot read property 'goto' of undefined,
    at PuppeteerProvider.cleanUpJob (/usr/src/app/build/puppeteer-provider.js:382:23),
    at runMicrotasks (<anonymous>),
    at processTicksAndRejections (internal/process/task_queues.js:94:5),
2020-02-10T21:49:56.434Z browserless:job Y99UZDR4RJTBDBKAK94H8A2VPUT55336: /: Inbound WebSocket request.,
2020-02-10T21:49:56.434Z browserless:job Y99UZDR4RJTBDBKAK94H8A2VPUT55336: Adding new job to queue.,
2020-02-10T21:49:56.434Z browserless:job Y99UZDR4RJTBDBKAK94H8A2VPUT55336: Getting browser.,
2020-02-10T21:49:56.434Z browserless:system Using pre-booted chrome: true,
2020-02-10T21:49:56.435Z browserless:system Waiting for chrome instance to be added back,
2020-02-10T21:50:56.408Z browserless:server Y99UZDR4RJTBDBKAK94H8A2VPUT55336: Recording timedout stat.,
2020-02-10T21:50:56.408Z browserless:job Y99UZDR4RJTBDBKAK94H8A2VPUT55336: Job has timed-out, closing the WebSocket.,
2020-02-10T21:50:56.409Z browserless:job Y99UZDR4RJTBDBKAK94H8A2VPUT55336: Cleaning up job,
2020-02-10T21:50:56.409Z browserless:job Y99UZDR4RJTBDBKAK94H8A2VPUT55336: No browser to cleanup, exiting,
2020-02-10T21:50:56.409Z browserless:server Current workload complete.,
2020-02-10T21:50:56.410Z browserless:job Y99UZDR4RJTBDBKAK94H8A2VPUT55336: Websocket closed early, removing from queue and closing.,
2020-02-10T21:50:56.410Z browserless:job Y99UZDR4RJTBDBKAK94H8A2VPUT55336: Removing job from queue and cleaning up.,
2020-02-10T21:50:56.410Z browserless:job Y99UZDR4RJTBDBKAK94H8A2VPUT55336: Cleaning up job,
2020-02-10T21:50:56.411Z browserless:job Y99UZDR4RJTBDBKAK94H8A2VPUT55336: No browser to cleanup, exiting,
2020-02-10T21:53:54.046Z browserless:job I450T6IIHF9NU8RM1XYP4G7QDDW0CLYE: /: Inbound WebSocket request.,
2020-02-10T21:53:54.046Z browserless:job I450T6IIHF9NU8RM1XYP4G7QDDW0CLYE: Adding new job to queue.,
2020-02-10T21:53:54.047Z browserless:job I450T6IIHF9NU8RM1XYP4G7QDDW0CLYE: Getting browser.,
2020-02-10T21:53:54.047Z browserless:system Using pre-booted chrome: true,
2020-02-10T21:53:54.047Z browserless:system Waiting for chrome instance to be added back,
```

**Comment by joelgriffith** [comment]
This looks a lot like a resource constraint to me. What’s the size of the machine you’re using to run browserless?

**Comment by POLAK93** [comment]
On Dev machine i5 16gb ram
On test env similar some Xeon with also 16gb ram. In machine metrics i don't see any problem with resources.

**Comment by joelgriffith** [comment]
Should be fixed in https://github.com/browserless/chrome/pull/581 hopefully

**Comment by joelgriffith** [comment]
Fix looks good for now, care to verify? Latest is built and out

**Comment by joelgriffith** [comment]
@POLAK93  is this still an issue you're experiencing?

**Comment by POLAK93** [comment]
I will check that on weekend.

**Comment by joelgriffith** [comment]
Going to close as I was able to run the following with success (hundreds of sessions):

```js
const puppeteer = require('puppeteer');

const run = () => {
  puppeteer.connect({
    browserWSEndpoint: 'ws://localhost:3000'
  }).then(async (browser) => {
    const page = await browser.newPage();
  
    await page.goto('https://www.example.com/');
    await page.setViewport({ width: 1920, height: 1080 });
    await page.pdf();
    browser.disconnect();
    run();
  });
}

run();
```

And with docker:

```sh
$ docker run --rm --name browserless -p 3000:3000 -e PREBOOT_CHROME=true -e KEEP_ALIVE=true browserless/chrome:latest
```
