### ISSUE TITLE
Max retries exceeded with url: /session (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

### ISSUE THREAD

**Issue by clown-0726** [browserless/chrome#639]
Hi team,

```
    def __init__(self):
        self.settings = get_project_settings()
        self.html_convertor = html2text.HTML2Text()
        self.html_convertor.ignore_links = True
        d = datetime.datetime.today()
        self.today = d.strftime('%Y%m%d')
        self.pages = 0
        self.s3resource = boto3.resource('s3', aws_access_key_id=self.settings.get('AWS_ACCESS_KEY_ID'), aws_secret_access_key=self.settings.get('AWS_SECRET_ACCESS_KEY'))
        # Set selenium
        chrome_options = webdriver.ChromeOptions()
        chrome_options.set_capability('browserless.token', '0fce1xxxxxxxxxxxxxxxxxxxxxf0a6e')
        chrome_options.add_argument("--no-sandbox")
        chrome_options.add_argument("--headless")

        self.driver = webdriver.Remote(
            command_executor='https://chrome.browserless.io/webdriver',
            desired_capabilities=chrome_options.to_capabilities()
        )
```

I brought the this service and I was always getting below error, am i making any wrong config? I am sure I am using the corrent api-key.

```
Traceback (most recent call last):
  File "C:\Users\lilcao\AppData\Local\Continuum\miniconda3\envs\hub-crawler\lib\site-packages\scrapy\crawler.py", line 177, in crawl
    return self._crawl(crawler, *args, **kwargs)
  File "C:\Users\lilcao\AppData\Local\Continuum\miniconda3\envs\hub-crawler\lib\site-packages\scrapy\crawler.py", line 181, in _crawl
    d = crawler.crawl(*args, **kwargs)
  File "C:\Users\lilcao\AppData\Local\Continuum\miniconda3\envs\hub-crawler\lib\site-packages\twisted\internet\defer.py", line 1613, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "C:\Users\lilcao\AppData\Local\Continuum\miniconda3\envs\hub-crawler\lib\site-packages\twisted\internet\defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File "C:\Users\lilcao\AppData\Local\Continuum\miniconda3\envs\hub-crawler\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Users\lilcao\AppData\Local\Continuum\miniconda3\envs\hub-crawler\lib\site-packages\scrapy\crawler.py", line 88, in crawl
    self.spider = self._create_spider(*args, **kwargs)
  File "C:\Users\lilcao\AppData\Local\Continuum\miniconda3\envs\hub-crawler\lib\site-packages\scrapy\crawler.py", line 100, in _create_spider
    return self.spidercls.from_crawler(self, *args, **kwargs)
  File "C:\Users\lilcao\Documents\filing-crawler\crawler\spiders\headless_test.py", line 29, in from_crawler
    spider = super(HeadlessTest, cls).from_crawler(crawler, *args, **kwargs)
  File "C:\Users\lilcao\AppData\Local\Continuum\miniconda3\envs\hub-crawler\lib\site-packages\scrapy\spiders\__init__.py", line 49, in from_crawler
    spider = cls(*args, **kwargs)
  File "C:\Users\lilcao\Documents\filing-crawler\crawler\spiders\headless_test.py", line 49, in __init__
    desired_capabilities=chrome_options.to_capabilities()
  File "C:\Users\lilcao\AppData\Local\Continuum\miniconda3\envs\hub-crawler\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\lilcao\AppData\Local\Continuum\miniconda3\envs\hub-crawler\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\lilcao\AppData\Local\Continuum\miniconda3\envs\hub-crawler\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Users\lilcao\AppData\Local\Continuum\miniconda3\envs\hub-crawler\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Users\lilcao\AppData\Local\Continuum\miniconda3\envs\hub-crawler\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 402, in _request
    resp = http.request(method, url, body=body, headers=headers)
  File "C:\Users\lilcao\AppData\Local\Continuum\miniconda3\envs\hub-crawler\lib\site-packages\urllib3\request.py", line 80, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "C:\Users\lilcao\AppData\Local\Continuum\miniconda3\envs\hub-crawler\lib\site-packages\urllib3\request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\lilcao\AppData\Local\Continuum\miniconda3\envs\hub-crawler\lib\site-packages\urllib3\poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\lilcao\AppData\Local\Continuum\miniconda3\envs\hub-crawler\lib\site-packages\urllib3\connectionpool.py", line 760, in urlopen
    **response_kw
  File "C:\Users\lilcao\AppData\Local\Continuum\miniconda3\envs\hub-crawler\lib\site-packages\urllib3\connectionpool.py", line 760, in urlopen
    **response_kw
  File "C:\Users\lilcao\AppData\Local\Continuum\miniconda3\envs\hub-crawler\lib\site-packages\urllib3\connectionpool.py", line 760, in urlopen
    **response_kw
  File "C:\Users\lilcao\AppData\Local\Continuum\miniconda3\envs\hub-crawler\lib\site-packages\urllib3\connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\lilcao\AppData\Local\Continuum\miniconda3\envs\hub-crawler\lib\site-packages\urllib3\util\retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='chrome.browserless.io', port=443): Max retries exceeded with url: /session (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

```

**Comment by joelgriffith** [comment]
Looks like certificate issues. Would you mind sending us an email at support at browserless dot io?

**Comment by clown-0726** [comment]
I have sent the email with account lilu.cao@orbitfin.ai. Please help.

**Comment by joelgriffith** [comment]
Followed up via email
